export const modelMetas = [
	{
		"name": "License Plate Detection Recognizer",
		"techname": "license-plate-detector-recognizer",
		"codename": "lpdr",
		"type": "detection",
		"desc": "Detection model that detects and recognize license plates of vehicles.",
		"version": "v1.0",
	},
	{
		"name": "Vehicle License Plate Detection",
		"techname": "vehicle-license-plate-detection-barrier-0106",
		"codename": "vlpd",
		"type": "detection",
		"desc": "Detection model that detects license plates of vehicles",
		"version": "v1.0-20ac20.4",
		"dict": {
			"vlpd": [
				"background",
				"vehicle",
				"license plate"
			]
		}
	},
	{
		"name": "Face Detection for CCTV view",
		"techname": "face-detection-retail-0004",
		"codename": "fdr",
		"type": "detection",
		"desc": "Detection model for faces",
		"version": "v1.0-2020.4",
		"dict": {
			"fdr": [
				"background",
				"face"
			]
		}
	},
	{
		"name": "Person Detection for CCTV view",
		"techname": "person-detection-retail-0013",
		"codename": "pdr",
		"type": "detection",
		"desc": "Detection model for people in indoor environments",
		"version": "v1.0-2020.4",
		"dict": {
			"pdr": [
				"background",
				"person"
			]
		}
	},
	{
		"name": "Person Detection for ADAS view",
		"techname": "pedestrian-detection-adas-0002",
		"codename": "pda",
		"type": "detection",
		"desc": "Detection model for pedestrians using Single Shot Multibox Detector(SSD)",
		"version": "v1.0-2020.4",
		"dict": {
			"pda": [
				"background",
				"person"
			]
		}
	},
	{
		"name": "Pedestrian Vehicle Bike Detection",
		"techname": "person-vehicle-bike-detection-crossroad-0078",
		"codename": "pvbd",
		"type": "detection",
		"desc": "Detection model to detect people, vehicles and bikes in outdoor environments",
		"version": "v1.0-2020.4",
		"dict": {
			"pvb": [
				"background",
				"person",
				"vehicle",
				"bike"
			]
		}
	},
	{
		"name": "Crowd Demographic Analysis",
		"techname": "semantic-segmentation-adas-0001",
		"codename": "cda",
		"type": "classification",
		"desc": "Model that performs semantic segmentation of an input image into different classes, with a focus on automotive driver assistance systems (ADAS) applications.",
		"version": "v1.0-2020.4"
	},
	{
		"name": "Vehicle Attributes Color",
		"techname": "vehicle-attributes-recognition-barrier-0039",
		"codename": "varb",
		"type": "classification",
		"desc": "Model that recognizes various attributes of vehicles, such as color and type",
		"version": "v1.0-2020.4",
		"dict": {
			"car_type": [
				"car",
				"bus",
				"truck",
				"van"
			],
			"color": [
				"white",
				"gray",
				"yellow",
				"red",
				"green",
				"blue",
				"black"
			]
		}
	},
	{
		"name": "Vehicle Attributes Type",
		"techname": "vcs19",
		"codename": "vcs19",
		"type": "classification",
		"desc": "Model that classifies up to 19 different classes of vehicles",
		"version": "v1.0-2020.4",
		"dict": {
			"vcs_label": [
				"5Ton",
				"BinTruck",
				"BoxTruck",
				"Bus",
				"Car",
				"Carrier",
				"CementTruck",
				"Crane",
				"Motorcycle",
				"OilTanker",
				"OpenBackTruck",
				"PickUp",
				"Road",
				"Taxi",
				"Tow",
				"TowFlat",
				"Tractor",
				"Trailer",
				"TrashTruck"
			]
		}
	},
	{
		"name": "Vehicle Attributes Make Model",
		"techname": "mobilenet128_vehicleRecognition",
		"codename": "make-model",
		"type": "classification",
		"desc": "Model that classifies the make and model of vehicles",
		"version": "v1.0-2020.4",
		"dict": {
			"make_label": [
				"Toyota",
				"Ford",
				"Volkswagen",
				"Honda",
				"Toyota",
				"BMW",
				"Opel",
				"Porsche",
				"Ford",
				"Volkswagen",
				"BMW",
				"Volkswagen",
				"Mini",
				"Jeep",
				"Honda",
				"Toyota",
				"Toyota",
				"Honda",
				"Mitsubishi",
				"Subaru",
				"Lada",
				"Lada",
				"Lada",
				"Ford",
				"Lada",
				"Toyota",
				"Opel",
				"Lada",
				"Audi",
				"Subaru",
				"Mercedes-Benz",
				"Toyota",
				"Honda",
				"Toyota",
				"Lada",
				"Nissan",
				"Skoda",
				"Mazda",
				"Porsche",
				"Kia",
				"Nissan",
				"Jeep",
				"Peugeot",
				"Lada",
				"Lada",
				"Lada",
				"Lada",
				"Ford",
				"BMW",
				"Nissan",
				"Toyota",
				"Lamborghini",
				"Mitsubishi",
				"Toyota",
				"BMW",
				"Audi",
				"Volkswagen",
				"Volkswagen",
				"Subaru",
				"Seat",
				"Opel",
				"Subaru",
				"Volkswagen",
				"Skoda",
				"Smart",
				"GAZ",
				"Toyota",
				"Seat",
				"Holden",
				"Fiat",
				"Mazda",
				"Chevrolet",
				"Audi",
				"BMW",
				"Toyota",
				"Mercedes-Benz",
				"Lada",
				"Mitsubishi",
				"Kia",
				"Toyota",
				"Land-Rover",
				"Toyota",
				"Opel",
				"Kia",
				"Hyundai",
				"Nissan",
				"Toyota",
				"Peugeot",
				"Toyota",
				"Chevrolet",
				"Kia",
				"Mazda",
				"Volkswagen",
				"Peugeot",
				"Dodge",
				"Fiat",
				"Chevrolet",
				"Mercedes-Benz",
				"Volkswagen",
				"Lamborghini",
				"Toyota",
				"Nissan",
				"Ford",
				"Audi",
				"Volkswagen",
				"Fiat",
				"Toyota",
				"Nissan",
				"Porsche",
				"Porsche",
				"Toyota",
				"Citroen",
				"Peugeot",
				"Volkswagen",
				"Hyundai",
				"Toyota",
				"Opel",
				"Ford",
				"Suzuki",
				"Hyundai",
				"Dodge",
				"Daewoo",
				"Jeep",
				"Volvo",
				"Nissan",
				"Toyota",
				"Hyundai",
				"Maruti Suzuki",
				"Chevrolet",
				"Kia",
				"Nissan",
				"Ferrari",
				"Toyota",
				"Ford",
				"BMW",
				"Chevrolet",
				"Honda",
				"Hyundai",
				"Nissan",
				"Land-Rover",
				"Peugeot",
				"Chevrolet",
				"Chevrolet",
				"Nissan",
				"Nissan",
				"Ford",
				"Opel",
				"Toyota",
				"Hyundai",
				"Nissan",
				"Land-Rover",
				"Ford",
				"BMW",
				"Toyota",
				"Land-Rover",
				"Citroen",
				"Renault",
				"Nissan",
				"Ford",
				"Porsche",
				"Peugeot",
				"Audi",
				"Peugeot",
				"Nissan",
				"Mazda",
				"Audi",
				"Ford",
				"Mazda",
				"Volvo",
				"Honda",
				"Skoda",
				"Jeep",
				"Maruti Suzuki",
				"BMW",
				"Toyota",
				"Hyundai",
				"Nissan",
				"Volkswagen",
				"Nissan",
				"Lada",
				"Audi",
				"Toyota",
				"BMW",
				"Volvo",
				"Audi",
				"Ford",
				"Honda",
				"Opel",
				"Toyota",
				"Nissan",
				"Lada",
				"Volkswagen",
				"Volvo",
				"GMC",
				"Jaguar",
				"Peugeot",
				"Porsche",
				"Ford",
				"Ford",
				"Volkswagen",
				"Honda",
				"Toyota",
				"Porsche",
				"BMW",
				"Peugeot",
				"Nissan",
				"Daewoo",
				"Hyundai",
				"Subaru",
				"BMW",
				"Audi",
				"Kia",
				"Mitsubishi",
				"Honda",
				"Toyota",
				"Citroen",
				"Chevrolet",
				"Smart",
				"Mitsubishi",
				"Mitsubishi",
				"Dodge",
				"Nissan",
				"BMW",
				"Renault",
				"BMW",
				"Toyota",
				"Chevrolet",
				"Nissan",
				"Land-Rover",
				"Porsche",
				"Jaguar",
				"Kia",
				"Bentley",
				"Mazda",
				"Toyota",
				"Suzuki",
				"Audi",
				"BMW",
				"Ferrari",
				"Volkswagen",
				"Acura",
				"BMW",
				"Honda",
				"Mitsubishi",
				"Citroen",
				"Hyundai",
				"BMW",
				"Opel",
				"Fiat",
				"Nissan",
				"Ferrari",
				"Nissan",
				"Kia",
				"Pagani",
				"Land-Rover",
				"Hyundai",
				"Nissan",
				"Honda",
				"Audi",
				"Nissan",
				"McLaren",
				"Toyota",
				"Abarth",
				"Nissan",
				"Toyota",
				"Nissan",
				"Ford",
				"Mazda",
				"Alfa Romeo",
				"Volkswagen",
				"Mini",
				"Ford",
				"Lamborghini",
				"Toyota",
				"Renault",
				"Jaguar",
				"Chevrolet",
				"Toyota",
				"Ferrari",
				"Opel",
				"Audi",
				"BMW",
				"RAM",
				"Lexus",
				"Fiat",
				"BMW",
				"Cadillac",
				"Ford",
				"Acura",
				"Nissan",
				"BMW",
				"Fiat",
				"Citroen",
				"Mercedes-Benz",
				"Skoda",
				"Land-Rover",
				"Mazda",
				"Citroen",
				"Peugeot",
				"Hyundai",
				"Fiat",
				"Peugeot",
				"Jaguar",
				"Aston Martin",
				"Dacia",
				"Renault",
				"Volvo",
				"Nissan",
				"Suzuki",
				"Toyota",
				"Lada",
				"Jaguar",
				"Mazda",
				"Audi",
				"Ford",
				"Mercedes-Benz",
				"Nissan",
				"Toyota",
				"Mitsubishi",
				"BMW",
				"Nissan",
				"Audi",
				"Lada",
				"Mitsubishi",
				"Audi",
				"Mitsubishi",
				"Chevrolet",
				"Skoda",
				"Mazda",
				"Abarth",
				"Toyota",
				"Ford",
				"Mercedes-Benz",
				"Peugeot",
				"Audi",
				"Fiat",
				"Lexus",
				"Hyundai",
				"Lada",
				"Saab",
				"Audi",
				"Volvo",
				"McLaren",
				"Hyundai",
				"Toyota",
				"Mazda",
				"Subaru",
				"Toyota",
				"Seat",
				"Nissan",
				"Audi",
				"Volkswagen",
				"BMW",
				"McLaren",
				"Fiat",
				"Toyota",
				"Audi",
				"Pontiac",
				"Bugatti",
				"Toyota",
				"Volkswagen",
				"Ferrari",
				"Nissan",
				"Alfa Romeo",
				"Mercedes-Benz",
				"Toyota",
				"Seat",
				"Volkswagen",
				"Porsche",
				"Daihatsu",
				"Citroen",
				"Porsche",
				"Jeep",
				"Chevrolet",
				"Ferrari",
				"Toyota",
				"Citroen",
				"Citroen",
				"Toyota",
				"Lexus",
				"Audi",
				"Porsche",
				"Dacia",
				"Ford",
				"Toyota",
				"Mitsubishi",
				"Mercedes-Benz",
				"Chevrolet",
				"BMW",
				"Volvo",
				"BMW",
				"Cadillac",
				"Opel",
				"Honda",
				"Mazda",
				"Peugeot",
				"Fiat",
				"Volvo",
				"Honda",
				"Infiniti",
				"Volkswagen",
				"BMW",
				"Mazda",
				"Ford",
				"Toyota",
				"Hyundai",
				"Subaru",
				"Nissan",
				"UAZ",
				"Bentley",
				"Honda",
				"Cadillac",
				"Skoda",
				"BMW",
				"Porsche",
				"Ford",
				"SsangYong",
				"Volkswagen",
				"Maserati",
				"Dodge",
				"Ford",
				"Kia",
				"Mitsubishi",
				"Lexus",
				"Audi",
				"Hyundai",
				"Ferrari",
				"Fiat",
				"Kia",
				"Opel",
				"Seat",
				"Mitsubishi",
				"Mercedes-Benz",
				"BMW",
				"Honda",
				"Mazda",
				"Toyota",
				"Rolls-Royce",
				"Acura",
				"UAZ",
				"Toyota",
				"Chevrolet",
				"Renault",
				"Cadillac",
				"Kia",
				"Subaru",
				"Tesla",
				"Vauxhall",
				"Audi",
				"Toyota",
				"Nissan",
				"Pontiac",
				"Audi",
				"Buick",
				"Tesla",
				"Volkswagen",
				"Ford",
				"Volvo",
				"Holden",
				"Toyota",
				"Audi",
				"Toyota",
				"Citroen",
				"Volkswagen",
				"Renault",
				"Lamborghini",
				"Mercedes-Benz",
				"Chrysler",
				"Alfa Romeo",
				"Pagani",
				"GMC",
				"UAZ",
				"Opel",
				"BMW",
				"Opel",
				"Peugeot",
				"Mazda",
				"Ferrari",
				"Vauxhall",
				"Mini",
				"Dodge",
				"Toyota",
				"Mercedes-Benz",
				"Volkswagen",
				"Nissan",
				"Toyota",
				"Lada",
				"Renault",
				"BMW",
				"Shelby",
				"Volkswagen",
				"Volkswagen",
				"Acura",
				"Lexus",
				"Scion",
				"Lexus",
				"Chevrolet",
				"Ford",
				"Honda",
				"Renault",
				"Mazda",
				"Volvo",
				"McLaren",
				"Holden",
				"Maserati",
				"Alfa Romeo",
				"Lancia",
				"Dodge",
				"Alfa Romeo",
				"Peugeot",
				"BMW",
				"Opel",
				"Seat",
				"Lincoln",
				"Mercedes-Benz",
				"Lamborghini",
				"Mercedes-Benz",
				"Lotus",
				"Skoda",
				"Bugatti",
				"McLaren",
				"Mazda",
				"Audi",
				"Jaguar",
				"Ford",
				"Jeep",
				"Toyota",
				"Alfa Romeo",
				"Toyota",
				"Ferrari",
				"Honda",
				"Hyundai",
				"Skoda",
				"BMW",
				"Aston Martin",
				"Acura",
				"Acura",
				"UAZ",
				"Maserati",
				"Lexus",
				"Dacia",
				"Alfa Romeo",
				"Isuzu",
				"BMW",
				"Renault",
				"Mercedes-Benz",
				"Holden",
				"Ferrari",
				"GMC",
				"Infiniti",
				"Renault",
				"Lexus",
				"Opel",
				"Toyota",
				"Lexus",
				"Ford",
				"GMC",
				"Ferrari",
				"Mitsubishi",
				"Mitsubishi",
				"Toyota",
				"Lada",
				"Datsun",
				"Nissan",
				"Honda",
				"Mazda",
				"Chrysler",
				"Hummer",
				"Citroen",
				"Nissan",
				"Peugeot",
				"Koenigsegg",
				"Suzuki",
				"Mazda",
				"Volkswagen",
				"Mazda",
				"Mercedes-Benz",
				"Tofas",
				"Kia",
				"BMW",
				"Nissan",
				"Lotus",
				"Saab",
				"Maruti Suzuki",
				"Toyota",
				"Chevrolet",
				"Porsche",
				"Mazda",
				"Acura",
				"Infiniti",
				"Toyota",
				"Opel",
				"Ford",
				"Mitsubishi",
				"SsangYong",
				"Ford",
				"Renault",
				"Mini",
				"Citroen",
				"Maserati",
				"Toyota",
				"Hummer",
				"Lincoln",
				"Lada",
				"Peugeot",
				"Peugeot",
				"Seat",
				"Aston Martin",
				"Maruti Suzuki",
				"Chrysler",
				"Scion",
				"Volvo",
				"Jeep",
				"Fiat",
				"Peugeot",
				"Ferrari",
				"Mercedes-Benz",
				"Renault",
				"Mazda",
				"BMW",
				"McLaren",
				"Toyota",
				"Alfa Romeo",
				"Iveco",
				"Toyota",
				"Saab",
				"Fiat",
				"Mercedes-Benz",
				"Mercedes-Benz",
				"Volvo",
				"Lamborghini",
				"Jeep",
				"Nissan",
				"Lamborghini",
				"Nissan",
				"Honda",
				"BMW",
				"Jeep",
				"Jaguar",
				"Porsche",
				"Peugeot",
				"Mitsubishi",
				"Honda",
				"Hyundai",
				"Mercedes-Benz",
				"Mercedes-Benz",
				"Lexus",
				"Chevrolet",
				"BMW",
				"Ferrari",
				"Hummer",
				"Dodge",
				"Citroen",
				"BMW",
				"Alfa Romeo",
				"Mercedes-Benz",
				"Mercedes-Benz",
				"Jaguar",
				"Peugeot",
				"Porsche",
				"Dodge",
				"Honda",
				"Hyundai",
				"Dodge",
				"BMW",
				"Mercedes-Benz",
				"Honda",
				"Audi",
				"Lancia",
				"SsangYong",
				"Renault",
				"Mazda",
				"Chrysler",
				"Toyota",
				"Ferrari",
				"Mercedes-Benz",
				"Mercedes-Benz",
				"Jaguar",
				"Volvo",
				"Nissan",
				"Toyota",
				"Toyota",
				"Mazda",
				"Opel",
				"Ford",
				"Ford",
				"Dodge",
				"Ferrari",
				"BMW",
				"Bentley",
				"Maruti Suzuki",
				"Nissan",
				"Buick",
				"Fiat",
				"Chevrolet",
				"Mercedes-Benz",
				"Renault",
				"Rolls-Royce",
				"Toyota",
				"Renault",
				"Holden",
				"Volvo",
				"Mercedes-Benz",
				"Audi",
				"Fiat",
				"Mazda",
				"Citroen",
				"Toyota",
				"Suzuki",
				"Subaru",
				"Toyota",
				"Fiat",
				"Toyota",
				"Toyota",
				"Renault",
				"Buick",
				"Mercedes-Benz",
				"Honda",
				"Mercury",
				"Audi",
				"BMW",
				"Cadillac",
				"Toyota",
				"Nissan",
				"Opel",
				"Mercedes-Benz",
				"Fiat",
				"Volkswagen",
				"RAM",
				"Fiat",
				"Mercedes-Benz",
				"Chrysler",
				"Ferrari",
				"Toyota",
				"Audi",
				"Mercedes-Benz",
				"Ford",
				"Lexus",
				"Toyota",
				"Renault",
				"Toyota",
				"Ferrari",
				"Mercedes-Benz",
				"Mitsubishi",
				"Abarth",
				"Toyota",
				"Porsche",
				"Buick",
				"Ford",
				"BMW",
				"Lancia",
				"Mercedes-Benz",
				"MG",
				"Mercedes-Benz",
				"Jaguar",
				"Honda",
				"Aston Martin",
				"SsangYong",
				"Lotus",
				"Ferrari",
				"Mercedes-Benz",
				"Kia",
				"Volvo",
				"Smart",
				"Audi",
				"Kia",
				"Chevrolet",
				"Bentley",
				"Toyota",
				"Citroen",
				"Cadillac",
				"Chrysler",
				"Ferrari",
				"Renault",
				"Mitsubishi",
				"Citroen",
				"Seat",
				"Land-Rover",
				"Lexus",
				"Acura",
				"Ford",
				"Mercedes-Benz",
				"Lancia",
				"Mitsubishi",
				"Porsche",
				"Citroen",
				"Rolls-Royce",
				"Mitsubishi",
				"Toyota",
				"Hyundai",
				"Chevrolet",
				"Hyundai",
				"Ford",
				"Holden",
				"Jeep",
				"Aston Martin",
				"Lexus",
				"Fiat",
				"Kia",
				"Kia",
				"Seat",
				"Ford",
				"Volvo",
				"Mercedes-Benz",
				"Suzuki",
				"Toyota",
				"Toyota",
				"Chevrolet",
				"Ford",
				"Nissan",
				"Renault",
				"Mercedes-Benz",
				"Peugeot",
				"Lamborghini",
				"Lexus",
				"Fiat",
				"Toyota",
				"Nissan",
				"Ford",
				"Tesla",
				"Fiat",
				"Infiniti",
				"Hyundai",
				"Mini",
				"Alpine",
				"Fiat",
				"Lada",
				"BMW",
				"SsangYong",
				"Nissan",
				"Scion",
				"Toyota",
				"Nissan",
				"DeLorean",
				"Nissan",
				"Holden",
				"Ford",
				"Aston Martin",
				"Toyota",
				"BMW",
				"Hyundai",
				"Mercedes-Benz",
				"Nissan",
				"BMW",
				"Volkswagen",
				"McLaren",
				"Ford",
				"Lexus",
				"Renault",
				"Mitsubishi",
				"Chevrolet",
				"Renault",
				"Ford",
				"Lexus",
				"Honda",
				"Great Wall",
				"Pontiac",
				"Pontiac",
				"Lincoln",
				"Jeep",
				"Nissan",
				"Alfa Romeo",
				"Volkswagen",
				"Subaru",
				"Chery",
				"BMW",
				"Maserati",
				"Cadillac",
				"Mercedes-Benz",
				"Infiniti",
				"Porsche",
				"Lexus",
				"Isuzu",
				"Nissan",
				"DeTomaso",
				"Citroen",
				"Mercedes-Benz",
				"Opel",
				"Maserati",
				"Hyundai",
				"Citroen",
				"BMW",
				"Citroen",
				"Mercedes-Benz",
				"Chevrolet",
				"Volvo",
				"Koenigsegg",
				"McLaren",
				"Buick",
				"Nissan",
				"Alfa Romeo",
				"BMW",
				"Tesla",
				"Toyota",
				"Trabant",
				"Dacia",
				"Volkswagen",
				"BMW",
				"Triumph",
				"Ferrari",
				"Volvo",
				"Audi",
				"BMW",
				"Renault",
				"Ferrari",
				"Toyota",
				"Dacia",
				"Cadillac",
				"Buick",
				"Mercedes-Benz",
				"Jaguar",
				"Fisker",
				"Toyota",
				"Mercedes-Benz",
				"Dodge",
				"Ferrari",
				"Nissan",
				"Toyota",
				"Porsche",
				"Dodge",
				"Mercedes-Benz",
				"Mercedes-Benz",
				"Rolls-Royce",
				"Mercedes-Benz",
				"Toyota",
				"Aston Martin",
				"Nissan",
				"Morris",
				"Mercedes-Benz",
				"Toyota",
				"Honda",
				"Renault",
				"Peugeot",
				"Fiat",
				"Toyota",
				"Honda",
				"Suzuki",
				"Ford",
				"Citroen",
				"Chevrolet",
				"BMW",
				"Honda",
				"Toyota",
				"Lincoln",
				"Buick",
				"Oldsmobile",
				"Lexus",
				"Maruti Suzuki",
				"Jeep",
				"Aston Martin",
				"Holden",
				"Mitsubishi",
				"Honda",
				"Izh",
				"Chrysler",
				"Cadillac",
				"Holden",
				"BMW",
				"Suzuki",
				"Cadillac",
				"Mercedes-Benz",
				"Peugeot",
				"Daihatsu",
				"Infiniti",
				"Volvo",
				"Ford",
				"Aston Martin",
				"Mercedes-Benz",
				"Opel",
				"Lamborghini",
				"Daihatsu",
				"Subaru",
				"Toyota",
				"Toyota",
				"Hyundai",
				"Jaguar",
				"Mitsubishi",
				"Ferrari",
				"BMW",
				"Nissan",
				"Lexus",
				"Geely",
				"Mazda",
				"Chevrolet",
				"GMC",
				"Datsun",
				"Cadillac",
				"Porsche",
				"Chrysler",
				"Lexus",
				"Audi",
				"Lexus",
				"Rolls-Royce",
				"Fiat",
				"Hyundai",
				"Seat",
				"Lexus",
				"Smart",
				"Jaguar",
				"Koenigsegg",
				"Ford",
				"Toyota",
				"Ferrari",
				"Nissan",
				"Lifan",
				"Mercedes-Benz",
				"Nissan",
				"Toyota",
				"Porsche",
				"Ferrari",
				"SsangYong",
				"Triumph",
				"Bentley",
				"Maruti Suzuki",
				"Mercedes-Benz",
				"Chevrolet",
				"Mercedes-Benz",
				"Fiat",
				"Buick",
				"Mercedes-Benz",
				"Alfa Romeo",
				"Nissan",
				"Fiat",
				"Pontiac",
				"Mercedes-Benz",
				"Mercedes-Benz",
				"Mercedes-Benz",
				"Dodge",
				"Infiniti",
				"Honda",
				"Chevrolet",
				"Chevrolet",
				"BMW",
				"ZAZ",
				"Volkswagen",
				"Toyota",
				"Honda",
				"Chevrolet",
				"Lexus",
				"Lotus",
				"Holden",
				"Honda",
				"BMW",
				"Ford",
				"Volvo",
				"Infiniti",
				"Mercedes-Benz",
				"Jeep",
				"Mitsubishi",
				"Honda",
				"Toyota",
				"BMW",
				"Daihatsu",
				"Hyundai",
				"Abarth",
				"Jeep",
				"Alfa Romeo",
				"Volkswagen",
				"Chevrolet",
				"Skoda",
				"Daihatsu",
				"Audi",
				"Infiniti",
				"Ford",
				"Toyota",
				"Koenigsegg",
				"Cadillac",
				"Fiat",
				"Lexus",
				"Hyundai",
				"Lexus",
				"Mercedes-Benz",
				"Ferrari",
				"Fiat",
				"Nissan",
				"Jaguar",
				"Fiat",
				"Peugeot",
				"Alfa Romeo",
				"Mercedes-Benz",
				"Dodge",
				"Dodge",
				"Renault",
				"Citroen",
				"Toyota",
				"Audi",
				"Buick",
				"Citroen",
				"Mercedes-Benz",
				"Pontiac",
				"Citroen",
				"Chrysler",
				"Ford",
				"Mercedes-Benz",
				"Rover",
				"Datsun",
				"KTM",
				"Porsche",
				"Opel",
				"Jaguar",
				"Peugeot",
				"BMW",
				"Peugeot",
				"BMW",
				"Chevrolet",
				"Mercedes-Benz",
				"Mercedes-Benz",
				"Mitsubishi",
				"Honda",
				"RAM",
				"Renault",
				"BMW",
				"Jaguar",
				"Lexus",
				"Honda",
				"Mercury",
				"Chrysler",
				"Ferrari",
				"Ford",
				"Volkswagen",
				"Toyota",
				"Lexus",
				"Saab",
				"Morris",
				"Peugeot",
				"Chevrolet",
				"Chevrolet",
				"Dodge",
				"Volkswagen",
				"Nissan",
				"MG",
				"Ferrari",
				"Opel",
				"Toyota",
				"Alfa Romeo",
				"Ford",
				"Volvo",
				"Fiat",
				"Bugatti",
				"Honda",
				"Mazda",
				"Mitsubishi",
				"Lexus",
				"Toyota",
				"Opel",
				"Daewoo",
				"Opel",
				"Chevrolet",
				"Nissan",
				"Lamborghini",
				"FSO",
				"Opel",
				"BMW",
				"Fiat",
				"Land-Rover",
				"Daihatsu",
				"Nissan",
				"Dodge",
				"Pontiac",
				"Lexus",
				"Toyota",
				"Toyota",
				"Chevrolet",
				"Mini",
				"Honda",
				"Mercedes-Benz",
				"BMW",
				"Ford",
				"Genesis",
				"Pontiac",
				"Jaguar",
				"Toyota",
				"Daihatsu",
				"Lexus",
				"Perodua",
				"Suzuki",
				"Geely",
				"Mazda",
				"Mercedes-Benz",
				"Aston Martin",
				"Nissan",
				"Ford",
				"BMW",
				"Mitsubishi",
				"Mahindra",
				"MG",
				"Jaguar",
				"Honda",
				"Lincoln",
				"Hyundai",
				"Honda",
				"Lexus",
				"Hyundai",
				"Fiat",
				"Mazda",
				"Peugeot",
				"Porsche",
				"Mercedes-Benz",
				"Mercedes-Benz",
				"Kia",
				"Peugeot",
				"Bentley",
				"Mazda",
				"Nissan",
				"BMW",
				"Nissan",
				"Chevrolet",
				"Lancia",
				"Toyota",
				"Daewoo",
				"Isuzu",
				"Infiniti",
				"Volkswagen",
				"Lexus",
				"Toyota",
				"Vauxhall",
				"GMC",
				"Infiniti",
				"Mazda",
				"Infiniti",
				"Ford",
				"Infiniti",
				"Mazda",
				"GAZ",
				"Izh",
				"Buick",
				"Nissan",
				"Honda",
				"Renault",
				"Hyundai",
				"MG",
				"Citroen",
				"HSV",
				"Chevrolet",
				"McLaren",
				"Lada",
				"Daihatsu",
				"Datsun",
				"Jaguar",
				"Infiniti",
				"Abarth",
				"Mazda",
				"Hyundai",
				"Holden",
				"Oldsmobile",
				"Mazda",
				"Mahindra",
				"Austin-Healey",
				"Alfa Romeo",
				"GMC",
				"Infiniti",
				"Toyota",
				"Mercedes-Benz",
				"Honda",
				"Honda",
				"Mercedes-Benz",
				"GAZ",
				"BMW",
				"Ford",
				"Infiniti",
				"Volkswagen",
				"Toyota",
				"GAZ",
				"Ferrari",
				"Mercedes-Benz",
				"Isuzu",
				"Chevrolet",
				"Suzuki",
				"Fiat",
				"BMW",
				"Ferrari",
				"Renault",
				"Skoda",
				"Audi",
				"Ford",
				"Fiat",
				"Citroen",
				"Alpina",
				"Peugeot",
				"Renault",
				"Porsche",
				"Holden",
				"BMW",
				"Toyota",
				"Infiniti",
				"Volvo",
				"Peugeot",
				"Mitsubishi",
				"Volkswagen",
				"Porsche",
				"Mazda",
				"Volkswagen",
				"Aston Martin",
				"Toyota",
				"Hyundai",
				"Mercedes-Benz",
				"Infiniti",
				"Volkswagen",
				"Renault",
				"Suzuki",
				"Chery",
				"Hyundai",
				"Ford",
				"Hyundai",
				"Caterham",
				"Renault",
				"BMW",
				"Lexus",
				"Nissan",
				"MG",
				"BMW",
				"Dodge",
				"Chevrolet",
				"Citroen",
				"Jaguar",
				"Fiat",
				"Kia",
				"Honda",
				"Fiat",
				"Mitsubishi",
				"Suzuki",
				"Volkswagen",
				"Citroen",
				"Mercedes-Benz",
				"Mitsubishi",
				"Mercedes-Benz",
				"Austin-Healey",
				"Audi",
				"Mercedes-Benz",
				"Datsun",
				"Lexus",
				"BYD",
				"Citroen",
				"Chevrolet",
				"Porsche",
				"Daewoo",
				"Iran Khodro",
				"Nissan",
				"Subaru",
				"W Motors",
				"Mercedes-Benz",
				"Fiat",
				"Toyota",
				"Mitsubishi",
				"Kia",
				"Lancia",
				"Isuzu",
				"Ferrari",
				"Kia",
				"Audi",
				"Infiniti",
				"Kia",
				"Renault",
				"Subaru",
				"Ferrari",
				"Abarth",
				"Mercedes-Benz",
				"Chevrolet",
				"Mercedes-Benz",
				"Saab",
				"Buick",
				"Ford",
				"Ferrari",
				"Mitsubishi",
				"Mercedes-Benz",
				"Honda",
				"Toyota",
				"Lotus",
				"Fiat",
				"Nissan",
				"Volvo",
				"BMW",
				"Alfa Romeo",
				"Chevrolet",
				"Honda",
				"Lincoln",
				"Land-Rover",
				"Mazda",
				"Fiat",
				"Mercedes-Benz",
				"Hyundai",
				"Ford",
				"Zenvo",
				"Holden",
				"BMW",
				"Autobianchi",
				"Toyota",
				"Holden",
				"Buick",
				"Lancia",
				"Chevrolet",
				"Mercedes-Benz",
				"Volvo",
				"Mitsubishi",
				"Chevrolet",
				"Mercedes-Benz",
				"Alfa Romeo",
				"Dodge",
				"Lamborghini",
				"Spyker",
				"Hyundai",
				"Chevrolet",
				"Triumph",
				"Hyundai",
				"Chevrolet",
				"Toyota",
				"Dacia",
				"Ford",
				"Hyundai",
				"Daihatsu",
				"Aston Martin",
				"Datsun",
				"Ferrari",
				"Pontiac",
				"Ariel",
				"W Motors",
				"Citroen",
				"BMW",
				"Infiniti",
				"Lifan",
				"Peugeot",
				"BMW",
				"Peugeot",
				"Ford",
				"Opel",
				"Ford",
				"Polski Fiat",
				"Dodge",
				"MG",
				"Mitsubishi",
				"Aston Martin",
				"Honda",
				"Peugeot",
				"Pontiac",
				"Proton",
				"Renault",
				"Land-Rover",
				"Mahindra",
				"Mini",
				"Ferrari",
				"Scion",
				"Buick",
				"Renault",
				"Infiniti",
				"Volvo",
				"Mitsubishi",
				"Acura",
				"Citroen",
				"Suzuki",
				"Volvo",
				"Oldsmobile",
				"Lifan",
				"Lada",
				"Mercedes-Benz",
				"Acura",
				"Fiat",
				"Toyota",
				"TagAZ",
				"Ferrari",
				"Cadillac",
				"Daihatsu",
				"Cadillac",
				"Saturn",
				"Dodge",
				"Toyota",
				"Morgan",
				"Saleen",
				"BMW",
				"Hennessey",
				"Scion",
				"Bertone",
				"Nissan",
				"Kia",
				"Nissan",
				"Lancia",
				"Toyota",
				"Fiat",
				"Mercedes-Benz",
				"Gumpert",
				"Chery",
				"Dodge",
				"Citroen",
				"Subaru",
				"Maserati",
				"Fiat",
				"Jaguar",
				"Acura",
				"Volvo",
				"Renault",
				"Mercedes-Benz",
				"Cadillac",
				"Infiniti",
				"Volkswagen",
				"Chevrolet",
				"Vauxhall",
				"Mitsubishi",
				"Toyota",
				"Mercedes-Benz",
				"Daihatsu",
				"HSV",
				"Suzuki",
				"Lamborghini",
				"Lexus",
				"Daihatsu",
				"Toyota",
				"SsangYong",
				"Chevrolet",
				"Citroen",
				"Toyota",
				"Audi",
				"Mercedes-Benz",
				"Fiat",
				"Renault",
				"International Harvester",
				"Toyota",
				"Citroen",
				"Nissan",
				"Lexus",
				"Ford",
				"Lada",
				"Saab",
				"Jaguar",
				"Porsche",
				"Subaru",
				"Volvo",
				"Ford",
				"Mercedes-Benz",
				"Lancia",
				"Alpina",
				"Infiniti",
				"McLaren",
				"Pontiac",
				"Peugeot",
				"Fiat",
				"Ferrari",
				"Morgan",
				"Renault",
				"Pontiac",
				"Ford",
				"Ford",
				"Jaguar",
				"Chevrolet",
				"Cadillac",
				"Peugeot",
				"Acura",
				"Noble",
				"Infiniti",
				"Mercedes-Benz",
				"TVR",
				"Aston Martin",
				"Acura",
				"Polski Fiat",
				"Lifan",
				"Mercedes-Benz",
				"BMW",
				"Renault",
				"Mercedes-Benz",
				"Kia",
				"Mercedes-Benz",
				"Mazda",
				"Mercedes-Benz",
				"Rolls-Royce",
				"Infiniti",
				"Toyota",
				"Nissan",
				"Toyota",
				"Renault",
				"Alfa Romeo",
				"Chrysler",
				"Alfa Romeo",
				"Vauxhall",
				"AMC",
				"Renault",
				"HSV",
				"Hyundai",
				"Lada",
				"Lotus",
				"Maybach",
				"Jaguar",
				"UAZ",
				"Piaggio",
				"Renault",
				"Oldsmobile",
				"GMC",
				"Lexus",
				"Alpina",
				"Subaru",
				"Ferrari",
				"Proton",
				"Honda",
				"SsangYong",
				"Audi",
				"Ferrari",
				"Alfa Romeo",
				"Lexus",
				"Peugeot",
				"GMC",
				"Nissan",
				"Mercedes-Benz",
				"Daihatsu",
				"Peugeot",
				"Mitsubishi",
				"Chery",
				"Mitsubishi",
				"Mercedes-Benz",
				"Perodua",
				"Opel",
				"Chrysler",
				"DS",
				"Volkswagen",
				"Ferrari",
				"Mini",
				"AMC",
				"Lancia",
				"Chrysler",
				"GMC",
				"Datsun",
				"Ford",
				"Saab",
				"Subaru",
				"Nissan",
				"GAZ",
				"Toyota",
				"Mercury",
				"Volvo",
				"Ford",
				"BAC",
				"Dodge",
				"Hillman",
				"Vortex",
				"Alpine",
				"Rimac",
				"BMW",
				"Mercedes-Benz",
				"Fiat",
				"Subaru",
				"Vauxhall",
				"Volvo",
				"Alfa Romeo",
				"Plymouth",
				"Volvo",
				"Opel",
				"Kia",
				"Lexus",
				"Kia",
				"Buick",
				"Volvo",
				"SsangYong",
				"Peugeot",
				"Seat",
				"Proton",
				"Isuzu",
				"Mercedes-Benz",
				"Alpina",
				"Cadillac",
				"Honda",
				"Chrysler",
				"Mitsubishi",
				"Dodge",
				"Suzuki",
				"Daihatsu",
				"Ferrari",
				"Lancia",
				"Alfa Romeo",
				"Subaru",
				"Buick",
				"Lada",
				"Citroen",
				"Mercedes-Benz",
				"Toyota",
				"Oldsmobile",
				"Citroen",
				"Mercedes-Benz",
				"Peugeot",
				"Fiat",
				"Mercedes-Benz",
				"Ferrari",
				"Tofas",
				"Proton",
				"Cadillac",
				"Renault",
				"BMW",
				"Bentley",
				"Maserati",
				"Ford",
				"Rolls-Royce",
				"Daihatsu",
				"Jaguar",
				"Lexus",
				"GMC",
				"Isuzu",
				"Opel",
				"Mercedes-Benz",
				"Lexus",
				"Mercedes-Benz",
				"Lancia",
				"Maybach",
				"Mercedes-Benz",
				"ZAZ",
				"Daewoo",
				"Saturn",
				"Honda",
				"Toyota",
				"Mercedes-Benz",
				"SsangYong",
				"Genesis",
				"Acura",
				"Fiat",
				"Mini",
				"Hillman",
				"Toyota",
				"Fiat",
				"Great Wall",
				"Nissan",
				"Proton",
				"Chevrolet",
				"Jensen",
				"TVR",
				"Chrysler",
				"Lexus",
				"Toyota",
				"Hyundai",
				"Mercedes-Benz",
				"RAM",
				"Ferrari",
				"Fiat",
				"Honda",
				"Infiniti",
				"Jaguar",
				"Volvo",
				"Lancia",
				"Lincoln",
				"Peugeot",
				"Chevrolet",
				"Kia",
				"Mazda",
				"Lancia",
				"Lexus",
				"Daewoo",
				"Volkswagen",
				"Citroen",
				"Seat",
				"Rover",
				"Mercedes-Benz",
				"Kia",
				"BMW",
				"Ferrari",
				"Maserati",
				"Chevrolet",
				"Lincoln",
				"Skoda",
				"Mercedes-Benz",
				"Scion",
				"Lexus",
				"Rolls-Royce",
				"Volvo",
				"Autobianchi",
				"MG",
				"Mercedes-Benz",
				"Triumph",
				"Vortex",
				"GMC",
				"Aston Martin",
				"Izh",
				"Rolls-Royce",
				"Aston Martin",
				"Daihatsu",
				"Isuzu",
				"Chevrolet",
				"Toyota",
				"Mercedes-Benz",
				"Piaggio",
				"Renault",
				"Suzuki",
				"Dodge",
				"Saab",
				"Lancia",
				"Chevrolet",
				"Alpina",
				"Aston Martin",
				"Honda",
				"Perodua",
				"Lancia",
				"AMC",
				"Rover",
				"Mercedes-Benz",
				"Lamborghini",
				"Triumph",
				"Holden",
				"Kia",
				"Mazda",
				"Mercedes-Benz",
				"Isuzu",
				"Nissan",
				"Morgan",
				"Peugeot",
				"Peugeot",
				"Citroen",
				"Plymouth",
				"Cadillac",
				"Hummer",
				"Oldsmobile",
				"Mercedes-Benz",
				"Ruf",
				"Mercedes-Benz",
				"Daihatsu",
				"Mercedes-Benz",
				"Daewoo",
				"Mercedes-Benz",
				"Rover",
				"Daihatsu",
				"Buick",
				"Suzuki",
				"Mazda",
				"MG",
				"Volkswagen",
				"Ford",
				"MG",
				"Willys",
				"Chery",
				"GAZ",
				"Renault",
				"Alfa Romeo",
				"BMW",
				"Hyundai",
				"MG",
				"Mazda",
				"Chevrolet",
				"Mercedes-Benz",
				"Bertone",
				"TVR",
				"Bentley",
				"Citroen",
				"Chrysler",
				"Toyota",
				"Peugeot",
				"Ford",
				"Holden",
				"Volkswagen",
				"SsangYong",
				"Chevrolet",
				"Alfa Romeo",
				"Austin-Healey",
				"Mitsubishi",
				"Kia",
				"Mercedes-Benz",
				"Renault",
				"Mercedes-Benz",
				"BMW",
				"Mazda",
				"Hyundai",
				"Buick",
				"Mercedes-Benz",
				"Citroen",
				"Caterham",
				"Citroen",
				"Suzuki",
				"Donkervoort",
				"Ford",
				"Lexus",
				"Opel",
				"Ligier",
				"Nissan",
				"Maserati",
				"Nissan",
				"Noble",
				"Mercedes-Benz",
				"Toyota",
				"Opel",
				"Mazda",
				"Toyota",
				"Mercedes-Benz",
				"Mazda",
				"Volkswagen",
				"Zastava",
				"Honda",
				"Mercedes-Benz",
				"Morgan",
				"Nissan",
				"Jeep",
				"Mercedes-Benz",
				"Mercedes-Benz",
				"Genesis",
				"Nissan",
				"Ford",
				"Daihatsu",
				"TVR",
				"Daihatsu",
				"Honda",
				"Lexus",
				"NSU",
				"Peugeot",
				"Renault",
				"Citroen",
				"Mercedes-Benz",
				"Mercedes-Benz",
				"DeTomaso",
				"Bentley",
				"Jaguar",
				"Volvo",
				"Hyundai",
				"Hyundai",
				"Mazda",
				"Suzuki",
				"Toyota",
				"Seat",
				"Kia",
				"Fiat",
				"Lexus",
				"Mitsubishi",
				"Alfa Romeo",
				"Toyota",
				"Chevrolet",
				"Lotus",
				"Infiniti",
				"Daewoo",
				"Mitsubishi",
				"Fiat",
				"Mercedes-Benz",
				"Maybach",
				"Mercedes-Benz",
				"Rover",
				"Lexus",
				"Mahindra",
				"Suzuki",
				"Chevrolet",
				"Maruti",
				"Borgward",
				"Subaru",
				"Fiat",
				"Mercedes-Benz",
				"Triumph",
				"Seat",
				"Nissan",
				"Lexus",
				"Subaru",
				"Wartburg",
				"Toyota",
				"Renault",
				"DS",
				"Honda",
				"Volvo",
				"Ford",
				"Nissan",
				"Mercedes-Benz",
				"Reliant",
				"TVR",
				"Infiniti",
				"Vauxhall",
				"Fiat",
				"Ford",
				"Mazda",
				"Nissan",
				"Pontiac",
				"Kia",
				"Scion",
				"Chevrolet",
				"Suzuki",
				"Geely",
				"Lincoln",
				"Haima",
				"Alfa Romeo",
				"Lamborghini",
				"Kia",
				"Opel",
				"Maserati",
				"Volvo",
				"Oldsmobile",
				"Proton",
				"Renault",
				"Renault",
				"Honda",
				"Alfa Romeo",
				"Lincoln",
				"Zastava",
				"Opel",
				"Maserati",
				"Mercedes-Benz",
				"Lexus",
				"Alfa Romeo",
				"Kia",
				"Chery",
				"Nash",
				"Volkswagen",
				"Reliant",
				"Volkswagen",
				"Chevrolet",
				"Citroen",
				"Volkswagen",
				"Bugatti",
				"BMW",
				"Ford",
				"ZAZ",
				"Citroen",
				"Cadillac",
				"Moskvich",
				"Mitsubishi",
				"Ferrari",
				"Ford",
				"Mercedes-Benz",
				"Peugeot",
				"Lincoln",
				"Chery",
				"Volkswagen",
				"Subaru",
				"Perodua",
				"Seat",
				"Renault",
				"Porsche",
				"FAW",
				"Ford",
				"Fiat",
				"Mercedes-Benz",
				"Rover",
				"Mercury",
				"Honda",
				"Mercedes-Benz",
				"Toyota",
				"Aston Martin",
				"Holden",
				"Geo",
				"Honda",
				"Maruti Suzuki",
				"ZAZ",
				"Ferrari",
				"Toyota",
				"Infiniti",
				"Volkswagen",
				"Chevrolet",
				"Lada",
				"Merkur",
				"Moskvich",
				"Renault",
				"MG",
				"Vauxhall",
				"FPV",
				"Citroen",
				"Lotus",
				"Toyota",
				"Volvo",
				"Citroen",
				"Subaru",
				"Isuzu",
				"Mercedes-Benz",
				"Izh",
				"Ford",
				"Lamborghini",
				"Skoda",
				"Audi",
				"Honda",
				"Tata",
				"Daewoo",
				"Suzuki",
				"Peugeot",
				"Ruf",
				"Lotus",
				"Changan",
				"Volkswagen",
				"Maybach",
				"Great Wall",
				"Daihatsu",
				"Ferrari",
				"Holden",
				"Ford",
				"Kia",
				"Oldsmobile",
				"Rossion",
				"Volkswagen",
				"Aixam",
				"Audi",
				"Lamborghini",
				"Lexus",
				"Honda",
				"Suzuki",
				"Lancia",
				"Austin",
				"Opel",
				"Vauxhall",
				"Mercedes-Benz",
				"Daewoo",
				"Ford",
				"Mercedes-Benz",
				"Ferrari",
				"Mercury",
				"Ford",
				"Nissan",
				"Triumph",
				"Ligier",
				"Infiniti",
				"Citroen",
				"Maserati",
				"Mercedes-Benz",
				"Geo",
				"Mercedes-Benz",
				"Microcar",
				"Lancia",
				"Mercedes-Benz",
				"Renault",
				"Lexus",
				"Saturn",
				"Chery",
				"Infiniti",
				"Mercedes-Benz",
				"Chevrolet",
				"Ford",
				"Tata",
				"Hyundai",
				"AMC",
				"Citroen",
				"Mitsubishi",
				"Daihatsu",
				"Maybach",
				"Lamborghini",
				"Marussia",
				"Volvo",
				"Lamborghini",
				"Mazda",
				"ZAZ",
				"Mazda",
				"Great Wall",
				"Proton",
				"Ford",
				"Ligier",
				"Maruti",
				"Lada",
				"Renault",
				"Mercedes-Benz",
				"Mitsubishi",
				"Subaru",
				"Chery",
				"ZAZ",
				"Wiesmann",
				"Volvo",
				"Ford",
				"BMW",
				"Holden",
				"Fiat",
				"Chery",
				"Citroen",
				"Toyota",
				"Infiniti",
				"Mercury",
				"Puma",
				"Mazda",
				"Holden",
				"Mercedes-Benz",
				"Nissan",
				"Chery",
				"Mercury",
				"Mercedes-Benz",
				"Nissan",
				"Nissan",
				"Nissan",
				"Mercedes-Benz",
				"Mercedes-Benz",
				"Subaru",
				"Dodge",
				"Mitsubishi",
				"Lamborghini",
				"Scion",
				"Kia",
				"HSV",
				"Toyota",
				"VUHL",
				"Edsel",
				"Lada",
				"Mahindra",
				"Suzuki",
				"Chevrolet",
				"Daimler",
				"Mazda",
				"Toyota",
				"MG",
				"Mercedes-Benz",
				"Lexus",
				"Mercedes-Benz",
				"Nissan",
				"Holden",
				"Mitsubishi",
				"Proton",
				"Mercury",
				"Maserati",
				"Mercedes-Benz",
				"Citroen",
				"Mercury",
				"Lexus",
				"Mitsubishi",
				"Peugeot",
				"Mercedes-Benz",
				"Mercedes-Benz",
				"Tata",
				"Kia",
				"Proton",
				"Renault",
				"Toyota",
				"Holden",
				"Ford",
				"Lincoln",
				"Nissan",
				"Jaguar",
				"Datsun",
				"Citroen",
				"Nissan",
				"Skoda",
				"Peugeot",
				"Renault",
				"Opel",
				"Holden",
				"Chrysler",
				"Mitsubishi",
				"Tata",
				"Morgan",
				"Renault",
				"Maybach",
				"Proton",
				"Volvo",
				"Suzuki",
				"Mitsubishi",
				"Skoda",
				"Volvo",
				"Saturn",
				"Kia",
				"Rolls-Royce",
				"Lotus",
				"Kia",
				"Infiniti",
				"Chevrolet",
				"Mazda",
				"Mazda",
				"Mercury",
				"AMC",
				"Opel",
				"Hyundai",
				"Volkswagen",
				"Pontiac",
				"Mazda",
				"Ferrari",
				"Renault",
				"Isuzu",
				"Suzuki",
				"Hyundai",
				"Innocenti",
				"Ford",
				"Tata",
				"Aixam",
				"Tianye",
				"Lamborghini",
				"SCG",
				"Saab",
				"UAZ",
				"Shelby",
				"Chery",
				"Honda",
				"Seat",
				"Isuzu",
				"Lincoln",
				"Austin",
				"Mercury",
				"DC",
				"Ford",
				"Ferrari",
				"Honda",
				"Kia",
				"Ginetta",
				"Chevrolet",
				"Cadillac",
				"Alpina",
				"Renault",
				"Chevrolet",
				"Pontiac",
				"Peugeot",
				"Ginetta",
				"Volkswagen",
				"Alfa Romeo",
				"Seat",
				"Messerschmitt",
				"Renault",
				"Daihatsu",
				"Lotus",
				"Toyota",
				"Isuzu",
				"Smart",
				"Rover",
				"Alfa Romeo",
				"Opel",
				"Izh",
				"Suzuki",
				"Mercedes-Benz",
				"Daihatsu",
				"Lincoln",
				"Seat",
				"Renault",
				"Fiat",
				"Chevrolet",
				"Hillman",
				"Nissan",
				"Ferrari",
				"Alfa Romeo",
				"Moskvich",
				"Buick",
				"Mazda",
				"Toyota",
				"Mercedes-Benz",
				"Alpina",
				"Mitsubishi",
				"Lancia",
				"Donkervoort",
				"Nissan",
				"Tata",
				"GAZ",
				"Daewoo",
				"Great Wall",
				"Honda",
				"Honda",
				"Alpina",
				"Mercedes-Benz",
				"Geely",
				"Chevrolet",
				"Lancia",
				"Mercedes-Benz",
				"Datsun",
				"Autobianchi",
				"Toyota",
				"Mazda",
				"RAM",
				"Ferrari",
				"Alpina",
				"Skoda",
				"Plymouth",
				"Ford",
				"Ford",
				"Chevrolet",
				"Mitsubishi",
				"BMW",
				"Opel",
				"Porsche",
				"Ford",
				"Mercedes-Benz",
				"Renault",
				"Jaguar",
				"Oldsmobile",
				"Geely",
				"Vespa",
				"Mahindra",
				"NSU",
				"Ford",
				"Chery",
				"Vauxhall",
				"Honda",
				"Lexus",
				"Subaru",
				"Perodua",
				"Lexus",
				"Holden",
				"Ferrari",
				"Alfa Romeo",
				"Lincoln",
				"SsangYong",
				"Vauxhall",
				"Chevrolet",
				"Rolls-Royce",
				"Mercedes-Benz",
				"Buick",
				"Hillman",
				"Morgan",
				"Maserati",
				"Ferrari",
				"Mercedes-Benz",
				"Mitsubishi",
				"Chevrolet",
				"Zenvo",
				"Iveco",
				"Ford",
				"Jaguar",
				"Mercedes-Benz",
				"Holden",
				"Hyundai",
				"Daihatsu",
				"Fiat",
				"Moskvich",
				"Holden",
				"Rover",
				"Ford",
				"Renault",
				"Maserati",
				"Mitsuoka",
				"Brilliance",
				"Ford",
				"Hyundai",
				"Buick",
				"Opel",
				"Volkswagen",
				"Lancia",
				"Jaguar",
				"Panoz",
				"Mazda",
				"Honda",
				"Koenigsegg",
				"Mercedes-Benz",
				"Pontiac",
				"Holden",
				"Ford",
				"Chevrolet",
				"Jaguar",
				"Chevrolet",
				"Mercedes-Benz",
				"Wiesmann",
				"Aston Martin",
				"Audi",
				"Peugeot",
				"Honda",
				"Holden",
				"Subaru",
				"Isuzu",
				"Ford",
				"Ford",
				"Volkswagen",
				"Mazda",
				"Seat",
				"Ferrari",
				"Nissan",
				"Packard",
				"Daihatsu",
				"Lancia",
				"Kia",
				"Daihatsu",
				"Austin",
				"GAZ",
				"Maserati",
				"Peel",
				"Great Wall",
				"Buick",
				"Mercedes-Benz",
				"Kia",
				"Tata",
				"Isuzu",
				"Moskvich",
				"Great Wall",
				"Premier",
				"Seat",
				"Chery",
				"Aston Martin",
				"Daihatsu",
				"Dodge",
				"Marussia",
				"Datsun",
				"GMC",
				"Nissan",
				"Saab",
				"Toyota",
				"Holden",
				"Oldsmobile",
				"Pegaso",
				"Maserati",
				"Oldsmobile",
				"Simca",
				"Nissan",
				"Abarth",
				"Hafei",
				"Infiniti",
				"Great Wall",
				"Toyota",
				"Bentley",
				"Chevrolet",
				"GMC",
				"Oldsmobile",
				"Simca",
				"Hyundai",
				"Peugeot",
				"Chatenet",
				"Wiesmann",
				"Suzuki",
				"Derways",
				"Kia",
				"Mazda",
				"Artega",
				"BYD",
				"TagAZ",
				"Infiniti",
				"DAF",
				"Foton",
				"SsangYong",
				"Saturn",
				"Renault",
				"Ford",
				"Ford",
				"Rover",
				"Austin-Healey",
				"Hyundai",
				"Bricklin",
				"McLaren",
				"Geely",
				"Zastava",
				"Mitsuoka",
				"Chery",
				"Mazda",
				"Daihatsu",
				"Cadillac",
				"UAZ",
				"Maserati",
				"HSV",
				"Renault",
				"Chevrolet",
				"Daihatsu",
				"Lamborghini",
				"Ferrari",
				"Maserati",
				"Holden",
				"Mazda",
				"Mercedes-Benz",
				"Bentley",
				"Suzuki",
				"Cisitalia",
				"Opel",
				"Chrysler",
				"Toyota",
				"Ferrari",
				"Citroen",
				"Renault",
				"Lincoln",
				"Mazda",
				"Talbot",
				"Wiesmann",
				"Daimler",
				"Great Wall",
				"TVR",
				"ZAZ",
				"Lamborghini",
				"Peugeot",
				"Geo",
				"Alfa Romeo",
				"AC",
				"Volvo",
				"Dodge",
				"Perodua",
				"Lamborghini",
				"DAF",
				"Infiniti",
				"Citroen",
				"Nissan",
				"Opel",
				"BMW",
				"Citroen",
				"Daewoo",
				"Isuzu",
				"Tata",
				"Mercedes-Benz",
				"Morris",
				"Nissan",
				"ZAZ",
				"Maserati",
				"Talbot",
				"Mercedes-Benz",
				"Kia",
				"Opel",
				"ZAZ",
				"Honda",
				"Daihatsu",
				"Fiat",
				"Daimler",
				"LDV",
				"Proton",
				"Fiat",
				"Aston Martin",
				"PUCH",
				"Datsun",
				"Dodge",
				"Facel Vega",
				"Seat",
				"Nissan",
				"Tata",
				"Mercedes-Benz",
				"Daihatsu",
				"Jaguar",
				"Rolls-Royce",
				"Chery",
				"Peugeot",
				"Renault",
				"Anadol",
				"Ligier",
				"Fiat",
				"Dodge",
				"Wiesmann",
				"Chevrolet",
				"Ford",
				"Jaguar",
				"Chevrolet",
				"Daewoo",
				"Perodua",
				"Mercedes-Benz",
				"TagAZ",
				"Infiniti",
				"UAZ",
				"Aston Martin",
				"Alpine",
				"Chery",
				"Nissan",
				"ZiL",
				"Mercedes-Benz",
				"Rover",
				"Ginetta",
				"Ford",
				"Triumph",
				"Lotus",
				"David Brown",
				"Isuzu",
				"Volkswagen",
				"Buick",
				"Pontiac",
				"Trabant",
				"Mazda",
				"Jaguar",
				"Chrysler",
				"Nissan",
				"Peugeot",
				"Daihatsu",
				"Peugeot",
				"Hudson",
				"Nissan",
				"Renault",
				"Chevrolet",
				"Hindustan",
				"Volkswagen",
				"Renault",
				"Alfa Romeo",
				"Daewoo",
				"Tucker",
				"Infiniti",
				"Dodge",
				"Mercedes-Benz",
				"Lancia",
				"Panhard",
				"Dodge",
				"Chevrolet",
				"Fiat",
				"Saab",
				"Saturn",
				"Buick",
				"Borgward",
				"Hyundai",
				"Renault",
				"Vauxhall",
				"Mahindra",
				"Matra",
				"Hyundai",
				"Mercedes-Benz",
				"Aston Martin",
				"Osca",
				"Wartburg",
				"Geely",
				"Aspark",
				"Subaru",
				"Ferrari",
				"Nissan",
				"Chevrolet",
				"Mazda",
				"Mercedes-Benz",
				"Mercury",
				"GAZ",
				"Mitsubishi",
				"Volvo",
				"Chevrolet",
				"Ford",
				"Dodge",
				"Bentley",
				"Daihatsu",
				"TagAZ",
				"Daihatsu",
				"Skoda",
				"Peugeot",
				"Jensen",
				"Borgward",
				"Daihatsu",
				"Aston Martin",
				"Proton",
				"Volkswagen",
				"Subaru",
				"Saturn",
				"Mercedes-Benz",
				"Matra",
				"Peugeot",
				"Stutz",
				"Daewoo",
				"MAN",
				"Mahindra",
				"Rover",
				"Vauxhall",
				"Mitsubishi",
				"Alfa Romeo",
				"Oldsmobile",
				"International Harvester",
				"Lifan",
				"Nissan",
				"Maruti",
				"Datsun",
				"Edsel",
				"Audi",
				"Nissan",
				"Simca",
				"Subaru",
				"Isuzu",
				"Koenigsegg",
				"Suzuki",
				"Oldsmobile",
				"Isdera",
				"Edsel",
				"Chatenet",
				"Matra",
				"Honda",
				"Great Wall",
				"Kaiser",
				"Mazda",
				"Lancia",
				"Volvo",
				"Isuzu",
				"Mitsuoka",
				"Mitsuoka",
				"Pontiac",
				"Kia",
				"Triumph",
				"Infiniti",
				"Geely",
				"Peugeot",
				"Bentley",
				"Lancia",
				"Mitsubishi",
				"Ferrari",
				"Aixam",
				"Bentley",
				"Ford",
				"Mercedes-Benz",
				"Chrysler",
				"Mercedes-Benz",
				"Volkswagen",
				"Fiat",
				"Fiat",
				"Oldsmobile",
				"Ford",
				"Talbot",
				"Mercedes-Benz",
				"Mastretta",
				"Vortex",
				"Hino",
				"Ferrari",
				"Matra",
				"Gurgel",
				"Lotus",
				"Kia",
				"McLaren",
				"Alvis",
				"MG",
				"LDV",
				"Ferrari",
				"Lincoln",
				"Alfa Romeo",
				"Fiat",
				"Hillman",
				"Lotus",
				"Microcar",
				"IKA",
				"Renault",
				"GMC",
				"Wartburg",
				"Bentley",
				"Ligier",
				"Plymouth",
				"Fiat",
				"BYD",
				"Mercedes-Benz",
				"Renault",
				"Rolls-Royce",
				"Mazda",
				"Ferrari",
				"Lancia",
				"Volvo",
				"Maserati",
				"Amphicar",
				"Buick",
				"Packard",
				"Panoz",
				"SsangYong",
				"Lotus",
				"Moskvich",
				"Mercedes-Benz",
				"MG",
				"Packard",
				"Citroen",
				"BMW",
				"TVR",
				"Aixam",
				"Volvo",
				"TagAZ",
				"Mazda",
				"Oldsmobile",
				"Austin",
				"Chery",
				"Mercury",
				"AC",
				"Skoda",
				"Vauxhall",
				"Mercedes-Benz",
				"Vauxhall",
				"Dodge",
				"Bugatti",
				"Humber",
				"Infiniti",
				"Nissan",
				"Edsel",
				"Bentley",
				"SsangYong",
				"Ford",
				"Lifan",
				"Jaguar",
				"Nissan",
				"Mahindra",
				"Panhard",
				"MG",
				"Renault",
				"Aixam",
				"Toyota",
				"Daihatsu",
				"Chevrolet",
				"Triumph",
				"Hyundai",
				"Autobianchi",
				"Tata",
				"Volkswagen",
				"Volkswagen",
				"Mitsuoka",
				"Donkervoort",
				"Jeep",
				"DKW",
				"Renault",
				"DeSoto",
				"Chevrolet",
				"Heinkel",
				"Renault",
				"Toyota",
				"Saturn",
				"Hyundai",
				"Perodua",
				"Suzuki",
				"Chevrolet",
				"Isuzu",
				"Citroen",
				"Renault",
				"Saturn",
				"Great Wall",
				"Healey",
				"Jeep",
				"Rover",
				"Bugatti",
				"FAW",
				"Daewoo",
				"Daihatsu",
				"Daihatsu",
				"Maserati",
				"Mitsubishi",
				"Tata",
				"Mitsubishi",
				"Chery",
				"ARO",
				"Citroen",
				"Sin Cars",
				"Nissan",
				"Facel Vega",
				"Luxgen",
				"Anadol",
				"Dodge",
				"Mercedes-Benz",
				"Jaguar",
				"Maruti",
				"MG",
				"Aixam",
				"Kia",
				"Nissan",
				"Mercedes-Benz",
				"Lamborghini",
				"Gurgel",
				"Cadillac",
				"Maruti",
				"Austin",
				"Chevrolet",
				"Mahindra",
				"Mahindra",
				"Toyota",
				"Bristol",
				"Tata",
				"FAW",
				"LuAZ",
				"Citroen",
				"Freightliner",
				"Gurgel",
				"Rolls-Royce",
				"Microcar",
				"Aixam",
				"Chery",
				"Tata",
				"Nash",
				"Daihatsu",
				"Renault",
				"Mahindra"
			],
			"model_label": [
				"Corolla",
				"Focus",
				"Golf",
				"Civic",
				"Camry",
				"5 Series",
				"Astra",
				"911",
				"Mustang",
				"Passat",
				"3 Series",
				"Polo",
				"Cooper",
				"Wrangler",
				"Accord",
				"Land Cruiser",
				"Mark II",
				"CR-V",
				"Lancer",
				"Impreza",
				"2114",
				"2107",
				"110",
				"Fiesta",
				"Priora",
				"RAV4",
				"Corsa",
				"2109",
				"A4",
				"Forester",
				"E-Class",
				"Land Cruiser Prado",
				"Fit",
				"Corona",
				"112",
				"Qashqai",
				"Octavia",
				"3",
				"Cayenne",
				"Sportage",
				"X-Trail",
				"Grand Cherokee",
				"308",
				"2106",
				"4x4 Niva",
				"21099",
				"2115",
				"Mondeo",
				"7 Series",
				"Skyline",
				"Vitz",
				"Aventador",
				"Pajero",
				"Caldina",
				"1 Series",
				"A6",
				"Transporter",
				"Beetle",
				"WRX",
				"Leon",
				"Zafira",
				"Legacy",
				"Tiguan",
				"Fabia",
				"Fortwo",
				"Volga",
				"Carina",
				"Ibiza",
				"Commodore",
				"500",
				"6",
				"Cruze",
				"R8",
				"X5",
				"Avensis",
				"S-Class",
				"Kalina",
				"Outlander",
				"Cee'd",
				"Vista",
				"Defender",
				"Chaser",
				"Insignia",
				"Sorento",
				"Santa Fe",
				"GT-R",
				"Allion",
				"206",
				"Crown",
				"Camaro",
				"Rio",
				"Demio",
				"Touran",
				"208",
				"Challenger",
				"Punto",
				"Corvette",
				"C-Class",
				"Touareg",
				"Huracan",
				"Hilux",
				"Silvia",
				"F-150",
				"A3",
				"Jetta",
				"Panda",
				"Prius",
				"Primera",
				"Carrera",
				"Panamera",
				"Sprinter",
				"C3",
				"207",
				"Caddy",
				"Tucson",
				"Harrier",
				"Meriva",
				"Ranger",
				"Grand Vitara",
				"Accent",
				"Charger",
				"Nexia",
				"Cherokee",
				"V40",
				"Sunny",
				"Ipsum",
				"Elantra",
				"Vitara",
				"Niva",
				"Picanto",
				"Juke",
				"458",
				"Premio",
				"Fusion",
				"M4",
				"Chevy",
				"HR-V",
				"i30",
				"Fairlady Z",
				"Discovery",
				"3008",
				"Silverado",
				"Lacetti",
				"Note",
				"Bluebird",
				"Escape",
				"Vectra",
				"Wish",
				"Sonata",
				"Micra",
				"Range Rover",
				"C-Max",
				"M3",
				"Cresta",
				"Range Rover Sport",
				"C4",
				"Megane",
				"Navara",
				"Kuga",
				"Boxster",
				"307",
				"TT",
				"2008",
				"March",
				"CX-5",
				"A5",
				"Falcon",
				"Miata",
				"S60",
				"Odyssey",
				"Superb",
				"Renegade",
				"Swift",
				"4 Series",
				"Yaris",
				"ix35",
				"Patrol",
				"Up",
				"Almera",
				"2105",
				"Q5",
				"Supra",
				"335",
				"V70",
				"RS 6",
				"Transit",
				"Integra",
				"Mokka",
				"Celica",
				"Tiida",
				"2108",
				"Scirocco",
				"V60",
				"Sierra",
				"F-Type",
				"508",
				"356",
				"Explorer",
				"KA",
				"Sharan",
				"Life",
				"HiAce",
				"Macan",
				"330",
				"Partner",
				"Teana",
				"Matiz",
				"Getz",
				"Outback",
				"E46",
				"Q7",
				"Optima",
				"Galant",
				"Jazz",
				"TownAce",
				"DS 3",
				"Aveo",
				"Forfour",
				"Colt",
				"ASX",
				"Ram",
				"Cefiro",
				"325",
				"Logan",
				"E36",
				"4Runner",
				"Malibu",
				"Wingroad",
				"Range Rover Evoque",
				"Cayman",
				"XF",
				"Cerato",
				"Continental GT",
				"RX-7",
				"Tacoma",
				"Jimny",
				"A8",
				"328",
				"488",
				"Multivan",
				"TL",
				"E30",
				"S2000",
				"L200",
				"Berlingo",
				"i20",
				"318",
				"Adam",
				"Doblo",
				"Maxima",
				"F430",
				"Cube",
				"Soul",
				"Huayra",
				"Freelander",
				"Solaris",
				"Pulsar",
				"Stream",
				"S3",
				"Altima",
				"12C",
				"Auris",
				"500",
				"AD Wagon",
				"Passo",
				"350Z",
				"S-MAX",
				"Familia",
				"Giulia",
				"Amarok",
				"One",
				"GT",
				"Gallardo",
				"ist",
				"Sport",
				"F-Pace",
				"Impala",
				"Hilux Surf",
				"LaFerrari",
				"Vivaro",
				"RS 3",
				"X3",
				"1500",
				"RX 300",
				"500C",
				"i8",
				"Escalade",
				"EcoSport",
				"MDX",
				"Pathfinder",
				"Z4",
				"500L",
				"C1",
				"M-Class",
				"Yeti",
				"Discovery Sport",
				"2",
				"C4 Picasso",
				"107",
				"Veloster",
				"500X",
				"5008",
				"E-Type",
				"Vantage",
				"Duster",
				"Clio",
				"XC90",
				"Sentra",
				"SX4",
				"Highlander",
				"2111",
				"XE",
				"RX-8",
				"A1",
				"Edge",
				"G-Class",
				"Serena",
				"Tundra",
				"Delica",
				"6 Series",
				"Murano",
				"S4",
				"2104",
				"Pajero Sport",
				"A7",
				"Lancer Evolution",
				"Equinox",
				"Rapid",
				"MX-5",
				"595",
				"Kluger",
				"Escort",
				"AMG C 63",
				"407",
				"S5",
				"Grande Punto",
				"RX 350",
				"Grand Starex",
				"2101",
				"9-3",
				"RS 4",
				"XC60",
				"570S",
				"i10",
				"Probox",
				"CX-7",
				"BRZ",
				"Platz",
				"Altea",
				"Laurel",
				"80",
				"New Beetle",
				"X1",
				"720S",
				"Ducato",
				"Fun Cargo",
				"Q3",
				"Firebird",
				"Chiron",
				"Ractis",
				"Crafter",
				"F12",
				"Terrano",
				"Giulietta",
				"220",
				"Gt 86",
				"Alhambra",
				"Kombi",
				"944",
				"Terios",
				"C5",
				"911 GT3",
				"Compass",
				"Lanos",
				"California",
				"LiteAce",
				"C4 Cactus",
				"2CV",
				"Estima",
				"LX 570",
				"RS 5",
				"Targa",
				"Sandero",
				"Galaxy",
				"Altezza",
				"Triton",
				"Mercedes-AMG GT",
				"Captiva",
				"i3",
				"S40",
				"M5",
				"CTS",
				"Combo",
				"Prelude",
				"Premacy",
				"108",
				"Tipo",
				"V50",
				"Stepwgn",
				"FX35",
				"Golf Plus",
				"X6",
				"CX-3",
				"F-Series Super Duty",
				"Mark X",
				"Avante",
				"Crosstrek",
				"370Z",
				"Buhanka",
				"Bentayga",
				"Airwave",
				"DeVille",
				"Citigo",
				"M2",
				"918 Spyder",
				"Bronco",
				"Actyon",
				"CC",
				"GranTurismo",
				"Viper",
				"F-250",
				"Spectra",
				"Eclipse",
				"GS 300",
				"SQ5",
				"i40",
				"Testarossa",
				"Bravo",
				"Carens",
				"Antara",
				"Mii",
				"Space Star",
				"CLA Shooting Brake",
				"2002",
				"NSX",
				"MPV",
				"Starlet",
				"Phantom",
				"RDX",
				"UAZ-3151",
				"FJ Cruiser",
				"Spark",
				"Captur",
				"CTS-V",
				"Venga",
				"XV",
				"Model S",
				"Astra",
				"100",
				"Fortuner",
				"Latio",
				"GTO",
				"RS 7",
				"Enclave",
				"Model X",
				"Passat CC",
				"B-MAX",
				"C30",
				"Cruze",
				"MR2",
				"TTS",
				"Raum",
				"Grand C4 Picasso",
				"Eos",
				"Twingo",
				"Murcielago",
				"200",
				"300",
				"4C",
				"Zonda",
				"Acadia",
				"UAZ-469",
				"Omega",
				"2 Series",
				"Agila",
				"106",
				"Bongo",
				"599",
				"Corsa",
				"Countryman",
				"Durango",
				"Noah",
				"230",
				"Lupo",
				"Rogue",
				"Nadia",
				"2113",
				"Scenic",
				"E92",
				"Cobra",
				"Phaeton",
				"Bora",
				"TLX",
				"RX 330",
				"FR-S",
				"IS 250",
				"Tahoe",
				"Territory",
				"Inspire",
				"Kangoo",
				"Axela",
				"S80",
				"675LT",
				"Captiva",
				"Quattroporte",
				"MiTo",
				"Delta",
				"Dart",
				"Spider",
				"Boxer",
				"F80",
				"Tigra",
				"Toledo",
				"Continental",
				"A-Class",
				"Countach",
				"CLK-Class",
				"Exige",
				"Kodiaq",
				"Veyron",
				"650S",
				"BT-50",
				"Q2",
				"XJ",
				"Fairlane",
				"Willys",
				"Soarer",
				"147",
				"Succeed",
				"360",
				"Torneo",
				"ix20",
				"Roomster",
				"E60",
				"Vanquish",
				"TSX",
				"NSX",
				"Patriot",
				"Levante",
				"GX 470",
				"Logan",
				"159",
				"D-Max",
				"M6",
				"Koleos",
				"300",
				"Colorado",
				"F40",
				"Yukon",
				"Q50",
				"Laguna",
				"LX 470",
				"Karl",
				"bB",
				"CT 200h",
				"Transit Connect",
				"Terrain",
				"F12tdf",
				"Mirage",
				"RVR",
				"Voxy",
				"Granta",
				"510",
				"Liberty",
				"Pilot",
				"CX-9",
				"300C",
				"H2",
				"C2",
				"Frontier",
				"205",
				"Agera",
				"Ignis",
				"Mazdaspeed 3",
				"Fox",
				"626",
				"C250",
				"Dogan",
				"Forte",
				"Z3",
				"Elgrand",
				"Elise",
				"900",
				"Baleno",
				"Windom",
				"Traverse",
				"Cayman GT4",
				"5",
				"ILX",
				"G35",
				"Aristo",
				"Kadett",
				"Crown Victoria",
				"3000GT",
				"Rexton",
				"Taurus",
				"Fluence",
				"Clubman",
				"C3 Picasso",
				"Ghibli",
				"Gaia",
				"H1",
				"Town Car",
				"Oka",
				"206 CC",
				"Expert",
				"Ateca",
				"DB11",
				"Wagon R",
				"PT Cruiser",
				"tC",
				"XC70",
				"Liberty",
				"147",
				"RCZ",
				"812 Superfast",
				"C200",
				"Sandero",
				"Capella",
				"X5 M",
				"P1",
				"C-HR",
				"Stelvio",
				"Daily",
				"Carina ED",
				"9-5",
				"Cinquecento",
				"CLA-Class",
				"A 45 AMG",
				"240",
				"Centenario",
				"CJ",
				"Avenir",
				"Diablo",
				"Presage",
				"Insight",
				"650i",
				"Patriot",
				"S-Type",
				"Carrera GT",
				"306",
				"Pajero Mini",
				"CR-X",
				"Tiburon",
				"C180",
				"GL-Class",
				"IS F",
				"Suburban",
				"X6 M",
				"Enzo",
				"H3",
				"Grand Caravan",
				"DS 4",
				"428i",
				"156",
				"SLS AMG",
				"SL-Class",
				"XKR",
				"207 CC",
				"928",
				"Caliber",
				"CR-Z",
				"Genesis Coupe",
				"Journey",
				"135i",
				"190",
				"Partner",
				"Cabriolet",
				"Ypsilon",
				"Kyron",
				"Trafic",
				"323",
				"200",
				"Tercel",
				"California T",
				"CLS-Class",
				"E 250",
				"X-Type",
				"S90",
				"Dualis",
				"Carina E",
				"Aygo",
				"Tribute",
				"Cascada",
				"Thunderbird",
				"Econoline",
				"Dakota",
				"308",
				"X4",
				"Flying Spur",
				"Alto",
				"Cedric",
				"Encore",
				"Fiorino",
				"Colorado",
				"180",
				"Duster",
				"Wraith",
				"Opa",
				"Grand Scenic",
				"Monaro",
				"850",
				"B-Class",
				"S8",
				"124",
				"Atenza",
				"DS 5",
				"Sienta",
				"Samurai",
				"Levorg",
				"Alphard",
				"Stilo",
				"Belta",
				"Etios",
				"Symbol",
				"LaCrosse",
				"B180",
				"Vezel",
				"Grand Marquis",
				"S1",
				"M235i",
				"SRX",
				"Corsa",
				"Versa",
				"Movano",
				"B200",
				"Freemont",
				"California",
				"2500",
				"Palio",
				"280",
				"Town and Country",
				"GTC4Lusso",
				"Venza",
				"SQ7",
				"320",
				"Galaxie",
				"GX 460",
				"Sienna",
				"Kadjar",
				"86",
				"250 GTO",
				"G 63 AMG",
				"Airtrek",
				"124 Spider",
				"Rush",
				"993",
				"Regal",
				"Sierra",
				"640",
				"Fulvia",
				"A 200",
				"MGB",
				"Vito",
				"XJ-S",
				"City",
				"DB5",
				"Korando",
				"Evora",
				"F355",
				"A 180",
				"Pro cee'd",
				"940",
				"Brabus",
				"S6",
				"Carnival",
				"Chevelle",
				"Mulsanne",
				"Sprinter Marino",
				"Jumper",
				"ATS",
				"Pacifica",
				"250",
				"Espace",
				"Carisma",
				"Xsara Picasso",
				"Exeo",
				"Series",
				"RX 450h",
				"RSX",
				"GT40",
				"E 220",
				"Stratos",
				"Diamante",
				"924",
				"DS",
				"Ghost",
				"Pajero iO",
				"Isis",
				"Starex",
				"Opala",
				"Genesis",
				"Expedition",
				"Torana",
				"Cherokee (XJ)",
				"DB9",
				"LC",
				"Seicento",
				"Niro",
				"Stinger",
				"Arosa",
				"Model A",
				"740",
				"E 200",
				"SX4 S-Cross",
				"Innova",
				"Verso",
				"TrailBlazer",
				"Tourneo Connect",
				"Vanette",
				"Talisman",
				"CLS 350",
				"406",
				"Miura",
				"LFA",
				"Multipla",
				"Verossa",
				"Titan",
				"Maverick",
				"Model 3",
				"Qubo",
				"G37",
				"Matrix",
				"Paceman",
				"A110",
				"Uno",
				"2103",
				"M Coupe",
				"Tivoli",
				"Grand Livina",
				"xB",
				"Vellfire",
				"Expert",
				"DMC 12",
				"Leaf",
				"Calais",
				"Grand C-MAX",
				"Lagonda",
				"Aurion",
				"8 Series",
				"Ioniq",
				"GLE-Class",
				"R'nessa",
				"M135i",
				"Gol",
				"570GT",
				"Capri",
				"LS 400",
				"Modus",
				"Montero",
				"Trax",
				"Master",
				"Shelby GT 500",
				"RC",
				"Mobilio",
				"Hover",
				"Grand Prix",
				"G8",
				"MKZ",
				"Comanche",
				"Xterra",
				"GT",
				"T4",
				"Liberty",
				"Tiggo",
				"635 CSi",
				"MC12",
				"Eldorado",
				"E 280",
				"QX56",
				"718 Boxster",
				"LS 460",
				"Bighorn",
				"Safari",
				"Pantera",
				"Saxo",
				"A 160",
				"Signum",
				"Grancabrio",
				"i30cw",
				"Xsara",
				"M1",
				"Jumpy",
				"Sprinter",
				"Bel Air",
				"C70",
				"CCX",
				"F1",
				"Envision",
				"Gloria",
				"GTV",
				"E28",
				"Roadster",
				"AE86",
				"601",
				"Dokker",
				"Corrado",
				"F10",
				"TR6",
				"FF",
				"V90",
				"A2",
				"Isetta",
				"Zoe",
				"FXX-K",
				"Duet",
				"Lodgy",
				"XT5",
				"Riviera",
				"E 63 AMG",
				"XK",
				"Karma",
				"Corona EXiV",
				"A 140",
				"Magnum",
				"348",
				"Tino",
				"Crown Majesta",
				"914",
				"Avenger",
				"A 170",
				"CLA45",
				"Dawn",
				"GLA-Class",
				"Porte",
				"Rapide",
				"Hardbody",
				"Minor",
				"C350",
				"Regius",
				"Ridgeline",
				"Twizy",
				"405",
				"Scudo",
				"Avalon",
				"Logo",
				"Liana",
				"F100",
				"C5 Tourer",
				"Sonic",
				"E21",
				"Legend",
				"Cressida",
				"Navigator",
				"LeSabre",
				"Cutlass",
				"SC 430",
				"Ertiga",
				"Wagoneer",
				"One-77",
				"Barina",
				"Chariot",
				"Domani",
				"2126",
				"Sebring",
				"XTS",
				"Astra",
				"Z8",
				"Splash",
				"Fleetwood",
				"Cabriolet",
				"307 CC",
				"Mira",
				"G35 Coupe",
				"P1800",
				"Shelby GT350",
				"Vulcan",
				"A 150",
				"Calibra",
				"Veneno",
				"Copen",
				"Tribeca",
				"Celsior",
				"Will",
				"Terracan",
				"XJ6",
				"Outlander Sport",
				"599XX",
				"E91",
				"Stagea",
				"ES 350",
				"Emgrand",
				"323F",
				"Caprice",
				"Canyon",
				"Go+",
				"CT6",
				"912",
				"Voyager",
				"RC 350",
				"RS Q3",
				"GS",
				"Silver Shadow",
				"126",
				"Creta",
				"Cordoba",
				"GS 350",
				"Roadster",
				"XJ220",
				"Regera",
				"Taunus",
				"Cami",
				"F50",
				"NV200",
				"Solano",
				"Citan",
				"Largo",
				"Matrix",
				"718 Cayman",
				"328",
				"Istana",
				"Spitfire",
				"Continental GTC",
				"Celerio",
				"CL-Class",
				"Cobalt",
				"W201",
				"128",
				"Skylark",
				"500",
				"75",
				"Caravan",
				"600",
				"Vibe",
				"CL500",
				"W123/C123",
				"W124",
				"Coronet",
				"Q60",
				"Freed",
				"Orlando",
				"Epica",
				"E70",
				"Chance",
				"Arteon",
				"Sequoia",
				"Element",
				"Corsa",
				"NX",
				"Esprit",
				"Ute",
				"Saber",
				"Gran-Turismo",
				"Model T",
				"XC40",
				"Q30",
				"300 SL",
				"Grand Wagoneer",
				"Libero",
				"Avancier",
				"Vanguard",
				"1M",
				"Sirion",
				"H-1",
				"Punto",
				"Commander",
				"Brera",
				"Vento",
				"Matiz",
				"Felicia",
				"YRV",
				"A6 allroad quattro",
				"QX70",
				"Everest",
				"Vios",
				"One:1",
				"ATS-V",
				"Croma",
				"LS 430",
				"Grandeur/Azera",
				"IS 200",
				"350",
				"288 GTO",
				"Albea",
				"Skyline GT-R",
				"XK120",
				"Sedici",
				"807",
				"8C Competizione",
				"SLK-Class",
				"Neon",
				"Nitro",
				"4",
				"Mehari",
				"Prius C",
				"S7",
				"Roadmaster",
				"C4 Coupe",
				"C 43 AMG",
				"Grand Am",
				"Xantia",
				"Crossfire",
				"Flex",
				"CLA250",
				"75",
				"Bluebird",
				"X-Bow",
				"959",
				"GT",
				"XJR",
				"1007",
				"850",
				"308 CC",
				"M140i",
				"Express",
				"GLK-Class",
				"CLS 63",
				"Grandis",
				"S660",
				"3500",
				"5",
				"F25",
				"E-Pace",
				"NX 300h",
				"Orthia",
				"Cougar",
				"Grand-Voyager",
				"Daytona",
				"Courier",
				"Saveiro",
				"iQ",
				"ES 300",
				"9000",
				"Mini",
				"504",
				"S-10",
				"Blazer",
				"Ramcharger",
				"LT",
				"Cima",
				"Midget",
				"FXX",
				"Ascona",
				"Progres",
				"Alfetta",
				"Figo",
				"S70",
				"Toro",
				"EB 110",
				"Brio",
				"Protege5",
				"Legnum",
				"NX 200t",
				"Corolla Verso",
				"Manta",
				"Winstorm",
				"Frontera",
				"Chevette",
				"Fuga",
				"Reventon",
				"Polonez",
				"Rekord",
				"E61",
				"Idea",
				"Range Rover Velar",
				"Cuore",
				"Presea",
				"Stratus",
				"G6",
				"IS 350",
				"Corolla II",
				"Avanza",
				"El Camino",
				"Cabrio",
				"Edix",
				"Viano",
				"E9",
				"Tourneo Courier",
				"G80",
				"Fiero",
				"D-Type",
				"JZX100",
				"Hijet",
				"IS 300",
				"Myvi",
				"Aerio",
				"MK",
				"Millenia",
				"W114",
				"DBS",
				"Z",
				"Cortina",
				"745",
				"Dingo",
				"Thar",
				"ZR",
				"XK8",
				"Capa",
				"MKX",
				"iLoad",
				"Ascot",
				"RX 400h",
				"Coupe",
				"Coupe",
				"RX-3",
				"607",
				"911 GT2",
				"A 250",
				"450",
				"Magentis",
				"4007",
				"Arnage",
				"Mazdaspeed6",
				"Prairie",
				"645",
				"Armada",
				"Avalanche",
				"Musa",
				"Camry Solara",
				"Espero",
				"Trooper",
				"M35",
				"Karmann Ghia",
				"GS 450h",
				"Cynos",
				"Vectra",
				"Suburban",
				"Q45",
				"B2200",
				"FX37",
				"Torino",
				"QX80",
				"Verisa",
				"GAZ-69",
				"2717",
				"Verano",
				"Bassara",
				"S-MX",
				"Sandero Stepway",
				"i20 WRC",
				"MGA",
				"Dyane",
				"ClubSport",
				"Monte Carlo",
				"540C",
				"2102",
				"Charade",
				"510 Wagon",
				"XFR",
				"G37 Sedan",
				"695",
				"MX-3",
				"Verna",
				"Trax",
				"Cutlass Supreme",
				"Protege",
				"XUV500",
				"3000",
				"166",
				"Envoy",
				"FX45",
				"Corolla Rumion",
				"G 350",
				"Mobilio Spike",
				"Crosstour",
				"R129",
				"GAZ-24",
				"New Class",
				"Probe",
				"QX30",
				"T1",
				"MR-S",
				"GAZ-21",
				"275",
				"SLR McLaren",
				"KB",
				"C10",
				"S-Cross",
				"Strada",
				"X2",
				"Portofino",
				"Grand Espace",
				"Karoq",
				"RS 2",
				"Tourneo-Custom",
				"Egea/Tipo",
				"C4 Aircross",
				"B7",
				"404",
				"12",
				"550",
				"Rodeo",
				"218",
				"Echo",
				"QX60",
				"960",
				"Bipper",
				"Starion",
				"T2",
				"968",
				"MX-6",
				"Westfalia",
				"DB4",
				"Voltz",
				"Grand i10",
				"X-Class",
				"G37 Coupe",
				"T3",
				"Grand Modus",
				"Kizashi",
				"A15",
				"Grace",
				"Station Wagon",
				"Atos",
				"Seven",
				"Kwid",
				"F15",
				"LS 460l",
				"Figaro",
				"TF",
				"M240i",
				"Caravan",
				"Kalos",
				"C-Elysee",
				"XJ8",
				"127",
				"Cadenza",
				"Shuttle",
				"Barchetta",
				"Challenger",
				"Kei",
				"T-ROC",
				"Traction Avant",
				"GLC-Class",
				"eK",
				"CLS 500",
				"Sprite",
				"90",
				"190 SL",
				"1200",
				"IS 300h",
				"F3",
				"CX",
				"Rezzo",
				"Boxster/Cayman",
				"Lanos",
				"Samand",
				"Evalia",
				"R-2",
				"Lykan",
				"ML 63 AMG",
				"Linea",
				"Passo-Sette",
				"Pajero Junior",
				"Mohave",
				"Rally 037",
				"MU-X",
				"550",
				"Pride",
				"V8",
				"G35 Sedan",
				"Sedona",
				"5 Turbo",
				"Justy",
				"512",
				"Grande Punto",
				"GLE 350",
				"Corvair",
				"Heckflosse",
				"96",
				"Century",
				"Explorer Sport Trac",
				"330",
				"L300",
				"ML 350",
				"Elysion",
				"MasterAce",
				"Elan",
				"131",
				"Kicks",
				"V90 Cross Country",
				"F31",
				"1750 Berlina",
				"Chevy II / Nova",
				"FR-V",
				"MKC",
				"Range Rover Classic",
				"Biante",
				"Mobi",
				"560",
				"iMax",
				"Excursion",
				"ST1",
				"Caprice",
				"228i",
				"A112",
				"Soluna",
				"Statesman",
				"Special",
				"Thema",
				"Onix",
				"GLS",
				"Amazon",
				"FTO",
				"Volt",
				"C240",
				"155",
				"Super Bee",
				"LM002",
				"C8",
				"NF",
				"Celta",
				"TR4",
				"Kona",
				"Nubira",
				"Tarago",
				"Stepway",
				"Scorpio",
				"Galloper",
				"Move",
				"Volante",
				"Sunny",
				"612 Scaglietti",
				"Sunfire",
				"Atom",
				"Fenyr",
				"C3 Aircross",
				"507",
				"EX35",
				"Breez",
				"406 Coupe",
				"E83",
				"508 RXH",
				"Granada",
				"Kadett C",
				"Corcel",
				"126 p",
				"Ram Van",
				"F",
				"Dion",
				"Zagato",
				"Beat",
				"4008",
				"Bonneville",
				"Satria",
				"Clio Sport",
				"Evoque",
				"Scorpio",
				"1000",
				"512BB",
				"xD",
				"Electra",
				"R4",
				"Q70",
				"244",
				"Pajero TR4",
				"RL",
				"SM",
				"Carry",
				"945",
				"442",
				"X60",
				"Samara",
				"W108",
				"RLX",
				"Duna",
				"Agya",
				"Tager",
				"Mondial",
				"STS",
				"Gran Max",
				"DTS",
				"Ion",
				"Polara",
				"Proace",
				"3-Wheeler",
				"S7",
				"F48",
				"Venom GT",
				"iM",
				"Opel Astra",
				"NP200",
				"Grand Carnival",
				"Moco",
				"Lybra",
				"Previa",
				"Marea",
				"B220",
				"Apollo",
				"Fora",
				"Power Wagon",
				"BX",
				"Alcyone SVX",
				"Gransport",
				"Fullback",
				"XK150",
				"CL",
				"245",
				"19",
				"R-Class",
				"Brougham",
				"QX50",
				"Voyage",
				"Tracker",
				"Zafira",
				"Eclipse Cross",
				"Meru",
				"GLC 220d",
				"Sigra",
				"Maloo",
				"Every",
				"Super Trofeo",
				"RX 270",
				"Xenia",
				"Grand HiAce",
				"Musso",
				"HHR",
				"C3 Pluriel",
				"Urban Cruiser",
				"S2",
				"V-Class",
				"1100",
				"Vel Satis",
				"Scout",
				"Brevis",
				"Nemo",
				"Lafesta",
				"IS 200t",
				"Festiva",
				"Largus",
				"99",
				"Sovereign",
				"930",
				"Exiga",
				"Trucks",
				"Puma",
				"SLK 200",
				"Phedra",
				"B3",
				"FX50",
				"Senna",
				"Solstice",
				"408",
				"850",
				"Dino 246 GT",
				"Aero 8",
				"11",
				"LeMans",
				"Bronco II",
				"Fairmont",
				"XK140",
				"Vectra",
				"Seville",
				"Traveller",
				"Legend",
				"M600",
				"M37",
				"W209/C209",
				"Sagaris",
				"DB6",
				"EL",
				"125 p",
				"Smily",
				"W113",
				"501",
				"Wind",
				"E 55 AMG",
				"Stonic",
				"W126",
				"B2000",
				"C270",
				"Corniche",
				"M45",
				"Picnic",
				"Terrano II",
				"Mark X ZiO",
				"Estafette",
				"145",
				"New Yorker",
				"Montreal",
				"Nova",
				"AMX",
				"Megane Sport",
				"GTS",
				"Trajet",
				"Vesta",
				"Europa",
				"57 S",
				"C-Type",
				"Pickup",
				"Ape",
				"Latitude",
				"Delta 88",
				"Syclone",
				"RX 200t",
				"D3",
				"Baja",
				"456",
				"Saga",
				"Crossroad",
				"Xlv",
				"200",
				"Superamerica",
				"33",
				"RX 450",
				"309",
				"Jimmy",
				"Pixo",
				"300D",
				"Pyzar",
				"407 Coupe",
				"Pajero Pinin",
				"Qq",
				"Minica",
				"CL63",
				"Axia",
				"Crossland X",
				"Valiant",
				"7 Crossback",
				"Spacefox",
				"575M Maranello",
				"Moke",
				"Javelin",
				"Flaminia",
				"300M",
				"Sonoma",
				"120 Y",
				"RS200",
				"Turbo X",
				"Pleo",
				"Mistral",
				"Volga Siber",
				"Prius V",
				"Marauder",
				"480",
				"Laser",
				"Mono",
				"Neon SRT-4",
				"Imp",
				"Estina",
				"A310",
				"Concept_One",
				"E23",
				"A 190",
				"Siena",
				"Leone",
				"Vivaro",
				"142",
				"164",
				"Prowler",
				"Duett",
				"Ampera",
				"Quoris",
				"IS 220d",
				"Soul EV",
				"Lucerne",
				"340",
				"Rodius",
				"301",
				"Arona",
				"Iriz",
				"Gemini",
				"GLE 63",
				"B10",
				"XLR",
				"Rafaga",
				"LeBaron",
				"Space Wagon",
				"Daytona",
				"APV",
				"Feroza",
				"Dino",
				"Aurelia",
				"Alfasud",
				"360",
				"Grand National",
				"4x4 Urban",
				"AX",
				"W202",
				"Celica XX",
				"Toronado",
				"C6",
				"GLE 250",
				"505",
				"Talento",
				"380",
				"365",
				"Doblo",
				"Preve",
				"Series 62",
				"4CV",
				"M Roadster",
				"Brooklands",
				"Biturbo",
				"Ranchero",
				"Silver Cloud",
				"Ayla",
				"MK II",
				"LS 600h",
				"Vandura",
				"VehiCROSS",
				"Grandland X",
				"X156",
				"GS 430",
				"C126",
				"Flavia",
				"Landaulet",
				"GLC 250",
				"Sens",
				"Leganza",
				"Vue",
				"Acty",
				"Limo",
				"Marco Polo",
				"Korando Sports",
				"G70",
				"ZDX",
				"X1/9",
				"1300",
				"Hunter",
				"Mirai",
				"Brava",
				"Safe",
				"Quest",
				"Persona",
				"Prisma",
				"Interceptor",
				"Tuscan",
				"Stratus",
				"LS 600hl",
				"Granvia",
				"ix55",
				"W203",
				"PROMASTER",
				"612",
				"125",
				"Aerodeck",
				"G25",
				"XKSS",
				"PV544",
				"Thesis",
				"LS",
				"Bipper Tepee",
				"C1500",
				"Sephia",
				"Lantis",
				"Voyager",
				"ES 250",
				"Nubira",
				"CrossTouran",
				"C-Crosser",
				"600",
				"200",
				"CLS250",
				"Shuma",
				"Z1",
				"Barchetta",
				"3200 GT",
				"Fleetline",
				"MKS",
				"Favorit",
				"R320",
				"xA",
				"ES 300h",
				"Silver Spur",
				"460",
				"Bianchina",
				"3",
				"B250",
				"TR7",
				"Tingo",
				"Savana",
				"DB7",
				"2715",
				"Silver Spirit",
				"Cygnet",
				"Be-Go",
				"Rodeo",
				"Optra",
				"Curren",
				"GLC Coupe",
				"Porter",
				"8",
				"Cappuccino",
				"Intrepid",
				"9-2X",
				"Beta",
				"Bolt",
				"B6",
				"Virage",
				"S800",
				"Alza",
				"Delta S4",
				"Gremlin",
				"45",
				"CLC 200",
				"Espada",
				"Stag",
				"Kingswood",
				"K900",
				"B series",
				"SLC-Class",
				"Wizard",
				"Otti",
				"Plus 4",
				"403",
				"304",
				"Ami 6",
				"Road Runner",
				"ELR",
				"H3T",
				"Alero",
				"Vaneo",
				"CTR3",
				"Actros",
				"Mira Gino",
				"G 300",
				"Gentra",
				"600",
				"25",
				"Taft",
				"Park Avenue",
				"SJ 410",
				"Cosmo",
				"6",
				"E-Golf",
				"Fiesta WRC",
				"TD",
				"Willys-Overland",
				"Kimo",
				"Pobeda",
				"R5",
				"6C",
				"New Six",
				"Equus",
				"ZS",
				"CX-8",
				"Cavalier",
				"GL 350",
				"Fiat X1/9",
				"Chimaera",
				"Turbo R",
				"Ami 8",
				"Imperial",
				"Century",
				"203",
				"LTD",
				"Berlina",
				"CrossPolo",
				"Musso Sports",
				"Agile",
				"2000",
				"100",
				"i",
				"K3",
				"W208/C208",
				"Avantime",
				"SLK 55 AMG",
				"E12",
				"B2500",
				"H-100",
				"Cascada",
				"Atego",
				"C8",
				"7",
				"XM",
				"Karimun",
				"D8 GTO",
				"Freestyle",
				"LX 450",
				"Speedster",
				"JS 50",
				"Leopard",
				"Spyder",
				"NV400",
				"M12",
				"GL 320",
				"Prius C 5",
				"Commodore",
				"Autozam",
				"Cavalier",
				"CLK GTR",
				"RX-2",
				"XL1",
				"Yugo",
				"Ballade",
				"CL55",
				"Plus 8",
				"Lucino",
				"Cherokee (KL)",
				"GLK 350",
				"E 43 AMG",
				"G90",
				"Livina",
				"E series",
				"Taruna",
				"Griffith",
				"Rocky",
				"Concerto",
				"HS 250h",
				"Prinz",
				"204",
				"R19",
				"Space Tourer",
				"SLC 43",
				"500 E",
				"Mangusta",
				"Azure",
				"XJ40",
				"144",
				"Veracruz",
				"i45",
				"121",
				"XL-7",
				"Carina II",
				"Bocanegra",
				"Opirus",
				"Tempra",
				"RX 400",
				"Magna",
				"146",
				"Paseo",
				"Viva",
				"Cortina",
				"JX35",
				"Kalos",
				"i-MiEV",
				"500e",
				"GLK 220",
				"62 S",
				"GLC 43",
				"400",
				"LS 500h",
				"Bolero",
				"SJ Samurai",
				"Lumina",
				"800",
				"Isabella",
				"Vivio",
				"1500",
				"SLK 350",
				"TR3",
				"124",
				"AD Van",
				"LS 500",
				"Stella",
				"353",
				"Pronard",
				"Espana",
				"4 Crossback",
				"Vigor",
				"164",
				"Windstar",
				"Pao",
				"R107",
				"Robin",
				"Cerbera",
				"QX4",
				"Cavalier",
				"Ritmo",
				"Streetka",
				"929",
				"Rasheen",
				"G5",
				"Pregio",
				"iQ",
				"Astro",
				"SJ 413",
				"Emgrand X7",
				"Continental Mark V",
				"3",
				"33 Stradale",
				"Urraco",
				"Clarus",
				"Senator",
				"3500 GT",
				"440",
				"Ninety-Eight",
				"Exora",
				"Safrane",
				"21",
				"N-WGN",
				"SZ",
				"Zephyr",
				"750",
				"Vita",
				"250F",
				"G 320",
				"ES 330",
				"Sprint",
				"Besta",
				"Tiggo 5",
				"Metropolitan",
				"Atlas",
				"Scimitar",
				"Santana",
				"Spin",
				"C15",
				"Buggy",
				"Type 57",
				"M535i",
				"Landau",
				"968",
				"E-Mehari",
				"BLS",
				"412",
				"Xpander",
				"308 GT4",
				"Five Hundred",
				"W116",
				"306 Cabriolet",
				"Mark VIII",
				"M11",
				"181",
				"Traviq",
				"Kelisa",
				"127",
				"Express",
				"911 GT1",
				"Besturn",
				"Deluxe",
				"Dino",
				"Ponton",
				"Metro",
				"Monterey",
				"N-ONE",
				"CLC",
				"Celica GT-Four",
				"DB2",
				"Malibu",
				"Metro",
				"N360",
				"Ciaz",
				"Zaporozhets",
				"400",
				"Sai",
				"G20",
				"Pointer",
				"Evanda",
				"2329",
				"XR4Ti",
				"2140",
				"Duster Oroch",
				"ZT",
				"VX220",
				"GT",
				"C3 WRC",
				"3-Eleven",
				"Blade",
				"140",
				"GS",
				"Sambar",
				"Bellett",
				"E 430",
				"21261",
				"Bantam",
				"Jalpa",
				"120",
				"RS 2 Avant",
				"BR-V",
				"Xenon",
				"Tico",
				"Cervo",
				"104",
				"CTR",
				"Elite",
				"CS35",
				"Parati",
				"57",
				"Deer",
				"Atrai7",
				"SA Aperta",
				"Crewman",
				"Cougar",
				"K7",
				"88",
				"Q1",
				"Type 3",
				"City",
				"50",
				"Sesto Elemento",
				"GS 250",
				"Zest",
				"LJ80",
				"Beta Montecarlo",
				"A35",
				"Kadett B",
				"VXR8",
				"R170",
				"Cielo",
				"F-650",
				"GLE 450",
				"F60 America",
				"Mariner",
				"Anglia",
				"100NX",
				"Dolomite",
				"X-Too",
				"M30",
				"Visa",
				"Coupe",
				"SLK 250",
				"Tracker",
				"GL 450",
				"M.Go",
				"Kappa",
				"ML 250",
				"9",
				"LX 450d",
				"Sky",
				"Bonus",
				"I35",
				"C 55 AMG",
				"Astra",
				"Pinto",
				"Nexon",
				"Eon",
				"Pacer",
				"ZX",
				"Canter",
				"Esse",
				"62",
				"400 GT",
				"B2",
				"S60 Cross Country",
				"350 GT",
				"Proceed Marvie",
				"968 M",
				"Efini MS-8",
				"Wingle",
				"Waja",
				"Orion",
				"JS",
				"Gypsy",
				"Nadezhda",
				"16",
				"V220",
				"Toppo",
				"Ascent",
				"Arrizo 5",
				"965",
				"Roadster",
				"PV444",
				"Consul",
				"8",
				"Barina Spark",
				"Ulysse",
				"IndiS",
				"Acadiane",
				"Rukus",
				"Q70L",
				"Milan",
				"GTS",
				"Xedos 6",
				"Gemini",
				"CLS 400",
				"Urvan",
				"Very",
				"Sable",
				"SLC 200",
				"Almera Tino",
				"Sylphy",
				"Primastar",
				"SLK 200 Kompressor",
				"C 32 AMG",
				"Trezia",
				"Monaco",
				"380",
				"Estoque",
				"iA",
				"Bongo",
				"Senator",
				"Sera",
				"5",
				"Ranger",
				"2121",
				"KUV100",
				"MR Wagon",
				"MW",
				"Double-Six",
				"Luce",
				"Dyna",
				"Metro",
				"Unimog",
				"IS 220",
				"GLC 300",
				"President",
				"Spark",
				"Attrage",
				"Suprima S",
				"Montego",
				"Merak",
				"W219",
				"Xsara WRC",
				"Mountaineer",
				"IS 250C",
				"Endeavor",
				"806",
				"S124",
				"SLK 230 Kompressor",
				"Indica",
				"Rondo",
				"Perdana",
				"Alaskan",
				"Quantum",
				"Cascada",
				"Super Deluxe",
				"Continental Mark IV",
				"Rogue Sport",
				"Vanden Plas",
				"710",
				"DS3 WRC",
				"e-NV200",
				"100",
				"iON",
				"Mascott",
				"Monza",
				"Viva",
				"Concorde",
				"Space Runner",
				"Safari",
				"04/04/23",
				"Fuego",
				"Exelero",
				"GEN 2",
				"145",
				"Cultus Crescent",
				"Minicab",
				"Praktik",
				"780",
				"Aura",
				"Retona",
				"Silver Wraith",
				"Super Seven",
				"K2700",
				"I30",
				"SSR",
				"RX-4",
				"Vantrend",
				"Capri",
				"Eagle",
				"Diplomat",
				"Scoupe",
				"Passat (B8)",
				"Aztek",
				"Carol",
				"208",
				"Super 5",
				"117 Coupe",
				"X-90",
				"Excel",
				"Mini",
				"Freestar",
				"Tiago",
				"Crossline",
				"Admiral",
				"Terzo Millennio",
				"3",
				"9-7X",
				"UAZ-3159",
				"Daytona",
				"X1",
				"N-Box",
				"Marbella",
				"Panther",
				"Aviator",
				"Metro",
				"Marquis",
				"Avanti",
				"Sportka",
				"P4/5",
				"LaGreat",
				"Forte5",
				"G55",
				"Tacuma",
				"Allante",
				"B4",
				"18",
				"Meriva",
				"Tempest",
				"605",
				"G40",
				"Polo R WRC",
				"Tipo 33",
				"850",
				"KR200",
				"25",
				"Luxio",
				"2-Eleven",
				"Sparky",
				"Axiom",
				"Crossblade",
				"600",
				"Disco Volante",
				"Corsa Utility",
				"2125",
				"Forenza",
				"170",
				"Tanto",
				"MKT",
				"Leon X-PERIENCE",
				"6",
				"Campagnola",
				"Monza",
				"Minx",
				"Clipper",
				"F512 M",
				"1900",
				"408",
				"Rendezvous",
				"Sentia",
				"2000GT",
				"Pullman",
				"D5",
				"Express",
				"Appia",
				"D8",
				"Pino",
				"Hexa",
				"Chaika",
				"Magnus",
				"Sailor",
				"S600",
				"N600",
				"XD3",
				"Vario",
				"Otaka",
				"Montana",
				"Dedra",
				"G63 AMG 6x6",
				"Laurel",
				"Y10",
				"RunX",
				"Cronos",
				"5500",
				"166",
				"D4",
				"105",
				"Fury",
				"Aerostar",
				"1932 Ford",
				"K5 Blazer",
				"Emeraude",
				"327",
				"Sintra",
				"912E",
				"Country Sedan",
				"CLC-Class",
				"Clio Williams",
				"XJ13",
				"Bravada",
				"Vision",
				"Vespacar",
				"TUV300",
				"Ro 80",
				"Torino Talladega",
				"Tiggo 3",
				"Viva",
				"Clarity",
				"GS 400",
				"Domingo",
				"Viva",
				"GS 300h",
				"Jackaroo",
				"412",
				"2300",
				"Mark VII",
				"Korando Turismo",
				"Chevette",
				"1957 Chevrolet",
				"Silver Seraph",
				"CL203",
				"Wildcat",
				"Avenger",
				"Aeromax",
				"Khamsin",
				"Berlinetta Boxer",
				"R350",
				"Sigma",
				"Omega",
				"TS1 GT",
				"Massif",
				"Del Rey",
				"X308",
				"GLK 200",
				"Vectra",
				"Lantra",
				"Materia",
				"8V",
				"2141",
				"Epica",
				"Streetwise",
				"Contour",
				"Fluence Z.E.",
				"Bora",
				"Orochi",
				"M2",
				"E250",
				"Santro",
				"Reatta",
				"Kapitan",
				"cross up!",
				"Gamma",
				"X300",
				"Esperante",
				"Xedos",
				"Fit Shuttle",
				"CCR",
				"C 36 AMG",
				"Torrent",
				"Adventra",
				"E150",
				"Uplander",
				"XJR-15",
				"Cobalt SS",
				"SLC 180",
				"GT MF5",
				"DB2/4",
				"100 Coupe S",
				"305",
				"Jade",
				"TrailBlazer",
				"R1",
				"MU",
				"Aspire",
				"Crestline",
				"Routan",
				"RX",
				"Inca",
				"125 S",
				"NX",
				"Clipper",
				"Sonica",
				"Zagato",
				"Ray",
				"Max",
				"Allegro",
				"GAZ-67",
				"300S",
				"P50",
				"V240",
				"GSX",
				"A 210",
				"Avella",
				"Nano",
				"Amigo",
				"402/403/407",
				"X240",
				"Padmini",
				"SEAT Panda",
				"Tiggo 2",
				"DB10",
				"Midget",
				"Viper GTS-R",
				"B1",
				"mi-Do",
				"Safari",
				"KIX",
				"9-4X",
				"RAV4 Adventure",
				"Insignia",
				"Custom Cruiser",
				"Z-102",
				"Shamal",
				"Hurst/Olds",
				"1100",
				"Cherry",
				"1000",
				"Brio",
				"Q40",
				"V200",
				"Mega Cruiser",
				"Continental R",
				"LUV",
				"Typhoon",
				"Eighty-Eight",
				"1000",
				"Pony",
				"208 T16",
				"CH 26",
				"GT MF4",
				"Santana",
				"Aurora",
				"Amanti",
				"1300",
				"GT",
				"F0",
				"Vega",
				"EX25",
				"33",
				"Tunland",
				"Stavic",
				"SL",
				"Caravelle",
				"Country Squire",
				"ZX2",
				"800",
				"100-6",
				"H350",
				"SV1",
				"P1 LM",
				"CK",
				"101",
				"Viewt",
				"Fulwin",
				"Az-1",
				"Fourtrak",
				"Fleetwood Brougham",
				"Simbir",
				"Sebring",
				"Grange",
				"Alpine V6",
				"1955 Chevrolet",
				"Charmant",
				"Jarama",
				"750 Monza",
				"Mistral",
				"Combo",
				"Proceed",
				"C107",
				"Eight",
				"Fronte",
				"202",
				"Olympia",
				"Aspen",
				"Tazz",
				"Dino GT4",
				"C5 Aircross",
				"Dauphine",
				"Continental Mark III",
				"Grand Familia",
				"Horizon",
				"MF 3",
				"Limousine",
				"X200",
				"T350",
				"Slavuta",
				"Islero",
				"206 WRC",
				"Prizm",
				"2600",
				"Ace",
				"C303",
				"Omni",
				"Kenari",
				"Marzal",
				"66",
				"EX30",
				"C4 WRC",
				"Cabstar",
				"Admiral",
				"503",
				"GSA",
				"Rezzo",
				"Fargo",
				"Tigor",
				"G 290",
				"Marina",
				"Langley",
				"Tavria",
				"Indy",
				"Samba",
				"S202",
				"Visto",
				"Campo",
				"Vida",
				"Vamos",
				"Applause",
				"130",
				"SP250",
				"G10",
				"Savvy",
				"132",
				"DB4 GT Zagato",
				"Pinzgauer",
				"on-Do",
				"Ram SRT-10",
				"HK500",
				"1430",
				"Pulsar NX",
				"Super Ace",
				"Valente",
				"Coo",
				"420",
				"Silver Dawn",
				"A3",
				"J7",
				"17",
				"A1",
				"Ixo",
				"Argo",
				"Diplomat",
				"GT",
				"S-10 Blazer",
				"Ikon",
				"I-Pace",
				"Venture",
				"Damas",
				"Kancil",
				"W100",
				"Road Partner",
				"FX30",
				"UAZ-3153",
				"DB3S",
				"A610",
				"CrossEastar",
				"NV",
				"ZIL-41047",
				"Mercedes-AMG Project One",
				"100",
				"G50",
				"Endeavour",
				"TR8",
				"340R",
				"Speedback GT",
				"Aska",
				"Polo G40",
				"Sport Wagon",
				"Trans Sport",
				"1.1",
				"Persona",
				"420G",
				"Airflow",
				"Cedric Y31",
				"604",
				"Leeza",
				"J9",
				"Hornet",
				"NV350",
				"Sport Spider",
				"C K 10 Series",
				"Ambassador",
				"Iltis",
				"10",
				"Junior Zagato",
				"Tacuma",
				"48",
				"G37 Convertible",
				"Shadow",
				"MB100",
				"Prisma",
				"PL 17",
				"Bluesmobile",
				"Malibu Maxx",
				"Cronos",
				"9-3X",
				"S series",
				"Gran Sport",
				"BX7",
				"HB20",
				"20",
				"Firenza",
				"Xylo",
				"Bagheera",
				"XG",
				"G 240",
				"Valkyrie",
				"MT4",
				"311",
				"GC6",
				"OWL",
				"Brumby",
				"365 GTC/4",
				"Be-1",
				"Trans-Sport",
				"Eunos 500",
				"GLC 63",
				"Coupe",
				"GAZ-M1",
				"Town Box",
				"66",
				"K30",
				"Tempo",
				"Aspen",
				"R Type",
				"Mira Cocoa",
				"Estina",
				"Ceria",
				"130",
				"207 S2000",
				"Jensen-Healey",
				"BX5",
				"Cast",
				"DB3",
				"Jumbuck",
				"e-up!",
				"Dex",
				"Outlook",
				"300SEL 6.3",
				"Rancho",
				"202",
				"Blackhawk",
				"Racer",
				"TGL",
				"Goa",
				"216",
				"Astravan",
				"Verada",
				"Alfasud Sprint",
				"Intrigue",
				"Travelall",
				"X50",
				"NV300",
				"Zen",
				"1000",
				"Corsair",
				"Fox",
				"240 RS",
				"1200S",
				"Libero",
				"NPR",
				"CC8S",
				"Hustler",
				"Aurora",
				"Imperator 108i",
				"Villager",
				"Barooder",
				"Djet",
				"That's",
				"Steed 5",
				"Darrin",
				"8",
				"Astura",
				"P1900",
				"Impulse",
				"Himiko",
				"Galue",
				"Montana",
				"Joice",
				"2000",
				"J30",
				"LC",
				"Hoggar",
				"S1",
				"Aprilia",
				"Wagon",
				"Dino 206 GT",
				"Coupe GTi",
				"S2",
				"P100",
				"V220d",
				"Vision",
				"Metris",
				"Taro",
				"Regata",
				"238",
				"Cutlass Ciera",
				"Zephyr",
				"Murena",
				"T1",
				"MXT",
				"Corda",
				"Contessa",
				"410 SuperAmerica",
				"Murena",
				"BR-800",
				"Excel",
				"Lotze",
				"F1 LM",
				"TD 21",
				"5",
				"V80",
				"212 Export",
				"Nautilus",
				"Alfa 6",
				"133",
				"Super Minx",
				"Eclat",
				"Due",
				"Estanciera",
				"14",
				"TopKick",
				"Barkas",
				"S3",
				"Nova",
				"Voyager",
				"900",
				"Flyer",
				"ML 55 AMG",
				"Tondar 90",
				"Camargue",
				"CX-4",
				"500 Superfast",
				"Ardea",
				"262C",
				"Tipo 61",
				"770",
				"Rainier",
				"Twelve",
				"Roadster",
				"Korando Family",
				"Europa S",
				"401",
				"EQ",
				"GS",
				"Convertible",
				"H Van",
				"X7",
				"350i",
				"Crossover",
				"Laplander",
				"C10",
				"323C",
				"Vista Cruiser",
				"Maestro",
				"J11",
				"Villager",
				"Aceca",
				"1000 MB",
				"Lotus Carlton",
				"300 SLR",
				"Carlton",
				"600",
				"Type 41",
				"Super Snipe",
				"M35h",
				"120 Y",
				"Citation",
				"Mark VI",
				"Chairman",
				"E-450",
				"530",
				"XJR-9",
				"Gazelle",
				"Genio",
				"24",
				"Maestro",
				"Sandero R.S. 2.0",
				"Mega",
				"Coaster",
				"Delta",
				"C/K 3500 Series",
				"Acclaim",
				"XG350",
				"Giardiniera",
				"Indigo",
				"Derby",
				"Passat (B4)",
				"Le-Seyde",
				"D8 GT",
				"Jeepster Commando",
				"Junior",
				"Rapid",
				"Custom",
				"Prizm",
				"Kabine",
				"Rodeo",
				"T100",
				"Astra",
				"Entourage",
				"Bezza",
				"Palette",
				"Sail",
				"MU-7",
				"Evasion",
				"Alpine",
				"L series",
				"Voleex C30",
				"Silverstone",
				"Gladiator",
				"2000",
				"Type 55",
				"V5",
				"Alpheon",
				"Naked",
				"Opti",
				"Kyalami",
				"Cordia",
				"Bolt",
				"Raider",
				"Arrizo 3",
				"244",
				"C25",
				"R1",
				"1400 Bakkie",
				"Facel II",
				"Luxgen7-SUV",
				"A2",
				"Spirit",
				"V250d",
				"Mark VII",
				"Omni",
				"550",
				"Roadline",
				"X-Trek",
				"March NISMO",
				"T2",
				"Athon",
				"Supermini",
				"Cimarron",
				"Esteem",
				"A40 Farina",
				"Beat",
				"Quanto",
				"Verito",
				"Mark II Blit",
				"411",
				"Aria",
				"V2",
				"969",
				"C-Elysee WTCC",
				"Cascadia",
				"Carajas",
				"20",
				"Virgo",
				"500",
				"J3",
				"Sumo",
				"Statesman",
				"Gran Move",
				"Pulse",
				"NuvoSport"
			]
		}
	},
	{
		"name": "Intelligent Traffic Analysis",
		"techname": "semantic-segmentation-adas-0001",
		"codename": "ita",
		"type": "classification",
		"desc": "Model that performs semantic segmentation of an input image into different classes, with a focus on automotive driver assistance systems (ADAS) applications.",
		"version": "v1.0-2020.4"
	}
]
